### ISSUE TITLE
resources.h not found

### ISSUE THREAD

**Issue by Wasabi2007** [wjakob/nanogui#10]
Hi I try to use the nanogui in my projekt and added it as subdirectory to my cmake project.
As I see you collect the the resources with bin2c into a resources.h and resources.cpp but when I try to compile the projekt it seams the compiler can not find the header file.

Could you maybe give me a hint what went wrong?

**Comment by wjakob** [comment]
Hi,
the current release is meant to be added using ExternalProject_Add.

This will change at some point in the future, but for now you could also try the following fork: https://github.com/libigl/nanogui

Best,
Wenzel
