### ISSUE TITLE
MainLoop logical issue

### ISSUE THREAD

**Issue by xSaiteix** [wjakob/nanogui#100]
If I pass to the MainLoop zero then update thread won't work because here is a small logical error:

> if (refresh **>** 0) //must be >=
> {
>  //run update thread//
> }

From description of this function: 
> To disable the refresh timer, specify a **negative value** here.

If it possible fix it please. The error is in a file "common,cpp".

I came across this bug accidentally while studying the source code.

P.S.: how can I make pull request? I really want to help with the development of this library.  
You dont mind? =)

**Comment by wjakob** [comment]
Pull requests for minor issues like these are welcomed, but please understand that I don't have time to explain how Github works.
