### ISSUE TITLE
Nanogui compile 

### ISSUE THREAD

**Issue by chenhonghua** [wjakob/nanogui#11]
Hi,
Recently, I am using libigl,which contains nanogui. But I met a error when I compile it. Detail can be seen in:
https://github.com/libigl/libigl/issues/119#issuecomment-141067064
Look forward to your help!

**Comment by chenhonghua** [comment]
the assert occurred in the DenseStorage.h（line 86）

**Comment by chenhonghua** [comment]
“”EIGEN_MAKE_UNALIGNED_ARRAY_ASSERT(0xf)""

**Comment by wjakob** [comment]
Hi -- probably you are using a 32 bit compile? Does it still happen with 64 bit?

**Comment by wjakob** [comment]
Also, consider using a recent version of Visual Studio (e.g. 2015) -- these crashes are likely related to difficulties in enforcing SIMD alignment with the older C++03 standard.

**Comment by chenhonghua** [comment]
Thank you ! I recompile under 64 bit. All errors  dispear ! :)
Thank you again.
