### ISSUE TITLE
window offset when window size is too big at creation

### ISSUE THREAD

**Issue by 3dsman** [wjakob/nanogui#111]
i just clone the repo and compile the example files.
With the example 1 and 3 the window size is too high for my laptop screen (720). Everything work well but with vertical offset to the bottom for all interface but not mouse picking that left at the right place.

I'm on a linux mint platform.
It seem to be a glfw bug because glfwGetFramebufferSize return the big size even the windows is smaller but i'm not sure.

**Comment by wjakob** [comment]
I don't think there is anything we can do in this project if it's indeed a GLFW bug :(.

**Comment by 3dsman** [comment]
in my own glfw software i use this trick that avoid the bug.
but the screen size is different from the windows size so the -50 are arbitrary

const GLFWvidmode* mode = glfwGetVideoMode(glfwGetPrimaryMonitor());
GLFWwindow* window = glfwCreateWindow(mode->width - 50, mode->height -50, "my software", NULL, NULL);
