### ISSUE TITLE
GL_HALF_FLOAT not declared in glutil.h

### ISSUE THREAD

**Issue by thinkeneering** [wjakob/nanogui#121]
I noticed GL_HALF_FLOAT was not defined in glutil.h, so I tried to define it and assign it a value of 0x140B. However, when I did that, I got the error described below. Any ideas on how I could fix this issue?

`
1>------ Build started: Project: Nanogui-test, Configuration: Debug x64 ------
1>  main.cpp
1>C:\libraries\nanogui\nanogui\build\Debug\nanogui.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x398
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by thinkeneering** [comment]
My apologies for the multiple posts. I figured out what the issue was. I was not specifying the path for the static library. As for the GL_HALF_FLOAT constant that was undefined, I defined it in GL.h as follows:
`#define GL_HALF_FLOAT 0x140B`

The reason why I gave it this value was because the other existing data types declared in GL.h were defined contiguously.

**Comment by wjakob** [comment]
Ok, closing then.
