### ISSUE TITLE
Python bindings on Pypi ?

### ISSUE THREAD

**Issue by stuaxo** [wjakob/nanogui#122]
This would probably need a setup.py that could compile this, including ext modules (?) for the nanogui part, ability to generate a .whl file for windows.

- I'm a little fuzzy on some of the details when it comes to modules that use C/C++ though.

**Comment by wjakob** [comment]
Please feel free to contribute a PR with this functionality. Pybind11 includes an example project (https://github.com/pybind/cmake_example) that shows how to do this sort of thing.

Since this is a feature request and not an issue, I'll close the ticket.
