### ISSUE TITLE
BgFx as backend

### ISSUE THREAD

**Issue by maxprod2016** [wjakob/nanogui#125]
Hi,

Thank you for your project. NanoGUI will be greater if you allow to connect your project to BgFx. BgFx is a cross-platform rendering library with various backends : OpenGL/WebGL/Direct3D ... and a good number of platforms supported. (look at : https://github.com/bkaradzic/bgfx)

BgFx is mature and work already with NanoVG as static example (just drawing), the UI part use IMGUI.  (look at this example : https://github.com/bkaradzic/bgfx/blob/master/examples/20-nanovg/nanovg.cpp)

Connecting NanoVG with BgFx use a wrapper defined here : https://github.com/bkaradzic/bgfx/blob/master/examples/common/nanovg/nanovg_bgfx.h - I don't know if it's possible to make a wrapper because NanoGUI seem have strong dependencies with GLFW.

Anyway, NanoGUI is a great project and look very good. I hope that this project will have a glorious future.

Sincerely,
Max

**Comment by wjakob** [comment]
This is a feature request, closing as per CONTRIBUTING.md.
