### ISSUE TITLE
Compilation error in visual studio 2015

### ISSUE THREAD

**Issue by smit2013** [wjakob/nanogui#13]
Heres my output from compiler..

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because D:/projects/C++/naogui/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: bin2c, Configuration: Debug Win32 ------
3>------ Rebuild All started: Project: glew_p, Configuration: Debug Win32 ------
2>  Building Custom Rule D:/projects/C++/naogui/nanogui/CMakeLists.txt
2>  CMake does not need to re-run because D:\projects\C++\naogui\CMakeFiles\generate.stamp is up-to-date.
2>  bin2c.c
2>D:\projects\C++\naogui\nanogui\resources\bin2c.c(33): warning C4018: '<': signed/unsigned mismatch
2>D:\projects\C++\naogui\nanogui\resources\bin2c.c(34): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\string.h(552): note: see declaration of 'strdup'
3>  Building Custom Rule D:/projects/C++/naogui/nanogui/CMakeLists.txt
3>  CMake does not need to re-run because D:\projects\C++\naogui\CMakeFiles\generate.stamp is up-to-date.
3>  Creating directories for 'glew_p'
3>  Performing download step (DIR copy) for 'glew_p'
3>  No update step for 'glew_p'
3>  No patch step for 'glew_p'
3>  Performing configure step for 'glew_p'
3>  -- Configuring done
3>  -- Generating done
3>  -- Build files have been written to: D:/projects/C++/naogui/ext_build/src/glew_p-build
3>  Performing build step for 'glew_p'
3>  Microsoft (R) Build Engine version 14.0.23107.0
3>  Copyright (C) Microsoft Corporation. All rights reserved.
3>
3>  Build started 9/26/2015 10:35:49 PM.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" on node 1 (default targets).
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (1) is building "D:\projects\C++\naogui\ext_build\src\glew_p-build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
3>  InitializeBuildStatus:
3>    Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  FinalizeBuildStatus:
3>    Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
3>    Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ZERO_CHECK.vcxproj" (default targets).
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (1) is building "D:\projects\C++\naogui\ext_build\src\glew_p-build\glew.vcxproj" (3) on node 1 (default targets).
3>  InitializeBuildStatus:
3>    Creating "glew.dir\Debug\glew.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  ClCompile:
3>    D:\PROGRAMS\Visual Studio\VC\bin\CL.exe /c /ID:\projects\C++\naogui\ext_build\src\glew_p\include /I"C:\Program Files (x86)\Visual Leak Detector\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D GLEW_BUILD /D GLEW_NO_GLU /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"glew.dir\Debug\\" /Fd"glew.dir\Debug\glew.pdb" /Gd /TC /analyze- /errorReport:queue D:\projects\C++\naogui\ext_build\src\glew_p\src\glew.c
3>    glew.c
2>  bin2c.vcxproj -> D:\projects\C++\naogui\Debug\bin2c.exe
4>------ Rebuild All started: Project: glfw_p, Configuration: Debug Win32 ------
4>  Building Custom Rule D:/projects/C++/naogui/nanogui/CMakeLists.txt
4>  CMake does not need to re-run because D:\projects\C++\naogui\CMakeFiles\generate.stamp is up-to-date.
4>  Creating directories for 'glfw_p'
4>  Performing download step (DIR copy) for 'glfw_p'
4>  No update step for 'glfw_p'
4>  No patch step for 'glfw_p'
4>  Performing configure step for 'glfw_p'
4>CUSTOMBUILD : CMake error : The source directory "D:/projects/C++/naogui/ext_build/src/glfw_p" does not appear to contain CMakeLists.txt.
4>  Specify --help for usage, or press the help button on the CMake GUI.
3>  Lib:
3>    D:\PROGRAMS\Visual Studio\VC\bin\Lib.exe /OUT:"D:\projects\C++\naogui\ext_build\src\glew_p-build\Debug\glew.lib" /LIBPATH:"C:\Program Files (x86)\Visual Leak Detector\lib\Win32" /NOLOGO glew.dir\Debug\glew.obj
3>    glew.vcxproj -> D:\projects\C++\naogui\ext_build\src\glew_p-build\Debug\glew.lib
3>  CopyFilesToOutputDirectory:
3>    Copying file from "glew.dir\Debug\glew.pdb" to "D:\projects\C++\naogui\ext_build\src\glew_p-build\Debug\glew.pdb".
3>  FinalizeBuildStatus:
3>    Deleting file "glew.dir\Debug\glew.tlog\unsuccessfulbuild".
3>    Touching "glew.dir\Debug\glew.tlog\glew.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\glew.vcxproj" (default targets).
3>  InitializeBuildStatus:
3>    Creating "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  FinalizeBuildStatus:
3>    Deleting file "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
3>    Touching "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (default targets).
3>
3>  Build succeeded.
3>      0 Warning(s)
3>      0 Error(s)
3>
3>  Time Elapsed 00:00:04.20
3>  Performing install step for 'glew_p'
3>  Microsoft (R) Build Engine version 14.0.23107.0
3>  Copyright (C) Microsoft Corporation. All rights reserved.
3>
3>  Build started 9/26/2015 10:35:53 PM.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj" on node 1 (default targets).
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj" (1) is building "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (2) on node 1 (default targets).
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (2) is building "D:\projects\C++\naogui\ext_build\src\glew_p-build\ZERO_CHECK.vcxproj" (3) on node 1 (default targets).
3>  InitializeBuildStatus:
3>    Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  FinalizeBuildStatus:
3>    Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
3>    Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ZERO_CHECK.vcxproj" (default targets).
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (68,11)" does not exist in the project, and will be ignored.
3>  The target "_GeneratePrisForPortableLibraries" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.Net.CoreRuntime.targets (177,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (126,11)" does not exist in the project, and will be ignored.
3>  The target "AfterGenerateAppxManifest" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets (174,11)" does not exist in the project, and will be ignored.
3>  The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (149,61)" does not exist in the project, and will be ignored.
3>  Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (2) is building "D:\projects\C++\naogui\ext_build\src\glew_p-build\glew.vcxproj" (4) on node 1 (default targets).
3>  InitializeBuildStatus:
3>    Creating "glew.dir\Debug\glew.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  ClCompile:
3>    All outputs are up-to-date.
3>  Lib:
3>    All outputs are up-to-date.
3>    glew.vcxproj -> D:\projects\C++\naogui\ext_build\src\glew_p-build\Debug\glew.lib
3>  FinalizeBuildStatus:
3>    Deleting file "glew.dir\Debug\glew.tlog\unsuccessfulbuild".
3>    Touching "glew.dir\Debug\glew.tlog\glew.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\glew.vcxproj" (default targets).
3>  InitializeBuildStatus:
3>    Creating "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CustomBuild:
3>    All outputs are up-to-date.
3>  FinalizeBuildStatus:
3>    Deleting file "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
3>    Touching "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\ALL_BUILD.vcxproj" (default targets).
3>  InitializeBuildStatus:
3>    Creating "Win32\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  PostBuildEvent:
3>    setlocal
3>    "c:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
3>    if %errorlevel% neq 0 goto :cmEnd
3>    :cmEnd
3>    endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
3>    :cmErrorLevel
3>    exit /b %1
3>    :cmDone
3>    if %errorlevel% neq 0 goto :VCEnd
3>    :VCEnd
3>    -- Install configuration: "Debug"
3>    -- Installing: C:/Program Files (x86)/GLEW/lib/glew.lib
3>    CMake Error at cmake_install.cmake:32 (file):
3>      file INSTALL cannot copy file
3>      "D:/projects/C++/naogui/ext_build/src/glew_p-build/Debug/glew.lib" to
3>      "C:/Program Files (x86)/GLEW/lib/glew.lib".
3>
3>
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "c:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1 [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1. [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>  Done Building Project "D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj" (default targets) -- FAILED.
3>
3>  Build FAILED.
3>
3>  "D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj" (default target) (1) ->
3>  (PostBuildEvent target) ->
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "c:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1 [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1. [D:\projects\C++\naogui\ext_build\src\glew_p-build\install.vcxproj]
3>
3>      0 Warning(s)
3>      1 Error(s)
3>
3>  Time Elapsed 00:00:00.96
5>------ Rebuild All started: Project: nanogui, Configuration: Debug Win32 ------
5>  Building Custom Rule D:/projects/C++/naogui/nanogui/CMakeLists.txt
5>  CMake does not need to re-run because D:\projects\C++\naogui\CMakeFiles\generate.stamp is up-to-date.
5>  Running bin2c
5>  nanovg.c
5>d:\projects\c++\naogui\nanogui\ext\nanovg\src\stb_image.h(191): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
5>  d:\projects\c++\naogui\nanogui\ext\nanovg\src\stb_image.h(191): note: command-line arguments:  see previous definition of '_CRT_SECURE_NO_WARNINGS'
5>  resources.cpp
5>  glutil.cpp
5>  nanogui.cpp
5>  widget.cpp
5>  theme.cpp
5>  layout.cpp
5>  screen.cpp
5>D:\projects\C++\naogui\nanogui\src\screen.cpp(221): warning C4316: 'nanogui::Theme': object allocated on the heap may not be aligned 16
5>  label.cpp
5>  window.cpp
5>  popup.cpp
5>  checkbox.cpp
5>  button.cpp
5>  popupbutton.cpp
5>  combobox.cpp
5>D:\projects\C++\naogui\nanogui\src\combobox.cpp(11): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>D:\projects\C++\naogui\nanogui\src\combobox.cpp(31): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>  progressbar.cpp
5>  slider.cpp
5>  messagedialog.cpp
5>D:\projects\C++\naogui\nanogui\src\messagedialog.cpp(24): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
5>D:\projects\C++\naogui\nanogui\src\messagedialog.cpp(26): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
5>D:\projects\C++\naogui\nanogui\src\messagedialog.cpp(32): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>D:\projects\C++\naogui\nanogui\src\messagedialog.cpp(35): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>  textbox.cpp
5>  imagepanel.cpp
5>  imageview.cpp
5>  Generating Code...
5>  Compiling...
5>  vscrollpanel.cpp
5>  colorwheel.cpp
5>D:\projects\C++\naogui\nanogui\src\colorwheel.cpp(178): warning C4800: 'nanogui::ColorWheel::Region': forcing value to bool 'true' or 'false' (performance warning)
5>  graph.cpp
5>D:\projects\C++\naogui\nanogui\src\graph.cpp(31): warning C4018: '<': signed/unsigned mismatch
5>  Generating Code...
5>  nanogui.vcxproj -> D:\projects\C++\naogui\Debug\nanogui.lib
========== Rebuild All: 3 succeeded, 2 failed, 0 skipped ==========

**Comment by wjakob** [comment]
Hi,
I believe that this issue is fixed with the current repository version. Feel free to reopen if this is not the case.

Best,
Wenzel
