### ISSUE TITLE
custom shader conflict with screen->drawWigets()?

### ISSUE THREAD

**Issue by GryffindorZz** [wjakob/nanogui#145]
when I use costum shader to rendering 3d meshes, there are some problems occured.
Code:
while (!glfwWindowShouldClose(screen->glfwWindow()))
{
	glClearColor(0.1, 0.2, 0.3, 1);
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);		
	shader.Use();
	model.draw(shader);
	screen->drawWidgets();
	glfwSwapBuffers(screen->glfwWindow());
	glfwPollEvents();
}
Rendering results:
![image](https://cloud.githubusercontent.com/assets/18241063/19227536/ee23b376-8eed-11e6-9c16-4a2c6ce1a24d.png)

**But when i commented out `screen->drawWidgets();` , the results is normal.**
![image](https://cloud.githubusercontent.com/assets/18241063/19227569/51932856-8eee-11e6-84f1-2cb4f77b89cf.png)

the rendering model is phong model, and my shader reference Learning OpenGL shader:
http://www.learnopengl.com/code_viewer.php?type=header&code=shader

and bind mesh data to buffer is like this:

    glGenVertexArrays(1, &this->VAO);
    glGenBuffers(1, &this->VBO);
    glGenBuffers(1, &this->EBO);
  
    glBindVertexArray(this->VAO);
    glBindBuffer(GL_ARRAY_BUFFER, this->VBO);

    glBufferData(GL_ARRAY_BUFFER, this->vertices.size() * sizeof(Vertex), 
                 &this->vertices[0], GL_STATIC_DRAW);  

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, this->indices.size() * sizeof(GLuint), 
                 &this->indices[0], GL_STATIC_DRAW);

    // Vertex Positions
    glEnableVertexAttribArray(0);	
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), 
                         (GLvoid*)0);
    // Vertex Normals
    glEnableVertexAttribArray(1);	
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), 
                         (GLvoid*)offsetof(Vertex, Normal));
    // Vertex Texture Coords
    glEnableVertexAttribArray(2);	
    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), 
                         (GLvoid*)offsetof(Vertex, TexCoords));

    glBindVertexArray(0);

I don't know what I did wrong, I think maybe something wrong with buffer?

**Comment by GryffindorZz** [comment]
It seems like some vertices normal information has lost, like the following rendering results:
![image](https://cloud.githubusercontent.com/assets/18241063/19231179/2b690660-8f0b-11e6-8bb9-a2693d4b95d2.png)
![image](https://cloud.githubusercontent.com/assets/18241063/19231218/643bd8b4-8f0b-11e6-8886-4e7f01d1b3c2.png)

and when I comment out screen->drawWidgets(); it return normal. so does widgets buffer conflict with shader buffer?

**Comment by wjakob** [comment]
NanoVG sets various OpenGL flags, probably you need to turns of them back to values that your drawing code expects. (see the NanoVG site for details)

**Comment by GryffindorZz** [comment]
I found what's wrong with my code. In screen->drawWidgets(), it close GL_DEPTH_TEST , so when  draw widgets done, just enable GL_DEPTH_TEST.
