### ISSUE TITLE
Widgets are not shown when opening a full screen window on macOS

### ISSUE THREAD

**Issue by larsjueljensen** [wjakob/nanogui#149]
I have tried to use the code from example3 as a starting point for a new project. It works fine if I use the code as-is, but if I change

    GLFWwindow* window = glfwCreateWindow(800, 800, "example3", nullptr, nullptr);

into

    GLFWwindow* window = glfwCreateWindow(800, 800, "example3", glfwGetPrimaryMonitor(), nullptr);

the widgets is never shown.

**Comment by wjakob** [comment]
Hi @larsjueljensen,

potentially a GLFW issue. The following code from ``Screen`` works:

```cpp
        GLFWmonitor *monitor = glfwGetPrimaryMonitor();
        const GLFWvidmode *mode = glfwGetVideoMode(monitor);
        mGLFWWindow = glfwCreateWindow(mode->width, mode->height,
                                       caption.c_str(), monitor, nullptr);
```
