### ISSUE TITLE
Many WIN32 directives across the headers and sources which prevents to compile on commandline compilers

### ISSUE THREAD

**Issue by r-lyeh** [wjakob/nanogui#15]
VS IDE defines both `WIN32` and `_WIN32` directives.
However, command-line compilers, like VS, clang, gcc or Mingw will only look for `_WIN32` directive.

So underscore preffix is the correct way to detect Windows as it is the general rule for everybody.
This minor issue also happens in pybind11 :)

**Comment by wjakob** [comment]
fixed in both projects -- thanks.

**Comment by r-lyeh** [comment]
:+1:
