### ISSUE TITLE
Y-Mouse offset in the examples (Ubuntu 14.04)

### ISSUE THREAD

**Issue by fairlight1337** [wjakob/nanogui#152]
Hi,

When running the examples (`example1`, `example2`, `example3`), I have a mouse offset in positive Y direction for all widgets. Also when I move a window inside nanogui up to the upper border with that offset present, it is not drawn properly on that border. See pictures for details.

![ng1](https://cloud.githubusercontent.com/assets/1122132/19513206/6b581b4a-95ef-11e6-9365-5be4bed99463.png) ![ng2](https://cloud.githubusercontent.com/assets/1122132/19513208/6ca080b4-95ef-11e6-8fc1-b8b5e23fc1a9.png)

When I compile my own applications with nanogui, that doesn't happen. So something is off in the example code.

**Comment by wjakob** [comment]
Super-strange. How is your code different from the examples? What OS, graphics card, etc.?

**Comment by fairlight1337** [comment]
I'll look through it right now to see what's different. I basically built my application based on the examples, so I'll try to see what I did different.

Concerning your question:
 * Ubuntu 14.04.1 LTS
 * `lspci | grep VGA`: VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
 * `uname -a`: Linux winkler 3.13.0-37-generic 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Although that's a pretty weak graphics card, I'm actually using the OpenGL 3.3 core profile. The shaders work nicely. I'll update this when I find out what's different between the programs.

**Comment by fairlight1337** [comment]
Okay, at least I found how to remove the effect:

When resizing the `nanogui::Screen` in one of the examples from 1024x768 to 800x600, this doesn't happen (i.e. the offset is gone). After playing around with this a bit, I figured out that when the height is `> 685` (empirical analysis; don't ask me why this value), the offset starts appearing and grows with growing `Screen` height.

Funny enough, when I do a minimal example on my own, this again doesn't happen (even at 1024x768).

**Comment by fairlight1337** [comment]
On a related, but different note: The offender seems to be resizability of the `Screen` window.

When I add the `resizable` flag `false` (defaults to `true`) to the constructor of `Screen`, the problem goes away. In `example1.cpp`, I changed this:
```cpp
ExampleApplication() : nanogui::Screen(Eigen::Vector2i(1024, 768), "NanoGUI Test")
```
to this:
```cpp
ExampleApplication() : nanogui::Screen(Eigen::Vector2i(1024, 768), "NanoGUI Test", false)
```
And now there is no offset anymore, no matter what resolution I put in there. This was also what I did differently in my application. I'll let you know when I find out what makes the resizable window different in that respect.

**Comment by fairlight1337** [comment]
Sorry for all the spam, just keeping this up to date. I found where this is coming from. In `screen.cpp` I added an output to the framebuffer resize callback:
```cpp
glfwSetFramebufferSizeCallback(mGLFWWindow,                                                         
        [](GLFWwindow* w, int width, int height) {                                                      
            auto it = __nanogui_screens.find(w);                                                        
            if (it == __nanogui_screens.end())                                                          
                return;                                                                                 
            Screen* s = it->second;                                                                     
                                                                                                        
            if (!s->mProcessEvents)                                                                     
                return;                                                                                 
                                                                                                        
            ::std::cout << "resize to " << width << ", " << height << ::std::endl;                      
            s->resizeCallbackEvent(width, height);                                                      
        }                                                                                               
    );
```
And no matter what Y resolution I give `Screen` in the constructor, this always results in this output:
```bash
resize to 1024, 687
```
(haven't tested X)

**Comment by fairlight1337** [comment]
Here's more, a possible reason for its occurrence, and a possible cause why you're not seeing this.

I'm on a native resolution of 1366x768 (max on my monitor). As this only affects resizable windows, I assume that this is related to a maximum screen size. This issue https://github.com/glfw/glfw/issues/575 explains why this could be the case for GLFW applications. So it might actually be due to my Gnome panels covering part of the screen - I followed the suggestion from that other issue and removed the decoration:
```cpp
glfwWindowHint(GLFW_DECORATED, GL_FALSE);
```
With that, the margin got smaller (around the size of the window titlebar).

You could check whether this happens for you by setting a `Screen` height larger than your current desktop resolution.

One question: Why exactly are the arguments of
```cpp
bool Screen::resizeCallbackEvent(int, int)
```
not used and queried from the window/framebuffer?
```cpp
glfwGetFramebufferSize(mGLFWWindow, &fbSize[0], &fbSize[1]);                                        
glfwGetWindowSize(mGLFWWindow, &size[0], &size[1]);
```

Actually, the new values are not used, could that be? In the `resizeCallbackEvent()` function in `screen.cpp`, the function `resizeEvent()` is called. The only occurrence of that function is in `screen.h` (correct me if I missed another one).
That implementation says
```cpp
virtual bool resizeEvent(const Vector2i &) { return false; }
```
So the new GLFW window size is not reflected in the `nanogui::Screen` size. I understand that this is meant for subclassing (hence the `virtual`), but this might be why the default behavior adds the margin on top.

**Comment by fairlight1337** [comment]
Ha, this is probably related to some kind of sign error somewhere. Resizing the window changes the margin, but in the other direction:

<img src="https://cloud.githubusercontent.com/assets/1122132/19517047/3d89d888-95ff-11e6-83c5-7bddbab89b9e.png" width="200"><img src="https://cloud.githubusercontent.com/assets/1122132/19517049/40c95fe6-95ff-11e6-8e13-b3213f489f90.png" width="200"><img src="https://cloud.githubusercontent.com/assets/1122132/19517054/4406a89e-95ff-11e6-9400-2f1f1f2cc754.png" width="200">

**Comment by wjakob** [comment]
How strange (also that this doesn't happen here). I hope that you can track down what is causing it.

**Comment by fairlight1337** [comment]
Gotta work on something else now, will update later.

**Comment by fairlight1337** [comment]
This might be related: https://www.opengl.org/discussion_boards/showthread.php/164305-help-problems-resizing-GLX-windows

**Comment by wjakob** [comment]
So it's a bug then?

**Comment by fairlight1337** [comment]
It appears so, I'm still trying to figure out why this happens. This could be something in NanoVG, but I'm not sure.

So I don't have a solution (or definite reason) yet. Also, after my other comments above, I didn't have too much time to look into it yet. I'll gladly dig deeper.

**Comment by fairlight1337** [comment]
I'm on this, btw.

**Comment by fairlight1337** [comment]
I just did a test on a plain GLFW window to verify this; and it worked fine. Non-resizable and resizable windows both have no top margin and the resizable window behaves as expected (i.e. no top margin appears upon vertical resizing). I drew a triangle in the center of the window.

For comparison: `example1` has a rotating (GL) rect in the background; and that both moves down and changes size when the window is resized. So 3D geometry is also affected (besides the 2D interface), but not on a GLFW level.

I'll test plain NanoVG tomorrow when I find the time to set up a MWE. If NanoVG shows the same symptoms, then its on that level. If not, I'll dig into NanoGUI again.

**Comment by fairlight1337** [comment]
@wjakob Because its not happening on your end, may I ask what platform you're working on? Is it OSX?

**Comment by wjakob** [comment]
OSX 10.11.6, MacBook Pro (Retina, 15-inch, Early 2013), NVIDIA GeForce GT 650M 1024 MB

**Comment by wjakob** [comment]
I routinely use NanoGUI on Linux and Windows boxes as well. Nobody has ever reported this bug, so I think it's related to the configuration on your end.

**Comment by fairlight1337** [comment]
Alright, thanks. I'll try it on my MBP tomorrow as well and make sure this only happens on that one configuration (and isn't related to some stupid mistake I did).

Anyway, the Intel has been glitchy for a couple things for me already. I'll try my best.

**Comment by fairlight1337** [comment]
I tested this on two other machines. One was an MBP (late 2011, AMD Radeon I think) and one was another Linux box, similar to the one I had the issue on, but with a GTX instead of the Intel Graphics Controller (and much more RAM and a different CPU, but that shouldn't be relevant).

I couldn't reproduce the problem on either machine. I'm therefore closing the issue as it seems to be very specific (and I can't figure out why this happens).

For the sake of reference:

I dug into GLFW3's code and found that it doesn't actually use the `ResizeRequest` event (as noted in the [link from above](https://www.opengl.org/discussion_boards/showthread.php/164305-help-problems-resizing-GLX-windows)), but uses X's `ConfigureNotify` event already. So that's not related.

This is my hardware setup related to the issue:
 * `lspci | grep VGA`: `Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)`
 * `uname -a`: `Linux <...> 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Relevant part of `lshw`:
```
        *-display
             description: VGA compatible controller
             product: 3rd Gen Core processor Graphics Controller
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 09
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:43 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:5000(size=64)
```

Neither `gdb` nor `valgrind` have any remarks about problems in memory.

The problem only comes up when a window is marked as resizable - and then even without resizing it, a margin appears at the top, growing when the windows is dragged smaller (and shrinking when it is made taller - even beyond `y = 0`).

**Comment by fairlight1337** [comment]
Agreed; same here. I'm using OGRE-based [Gazebo](http://gazebosim.org/) a lot and am running into very similar issues, but just on this type of graphics adapter.

Anyway, if anybody has such problems with NanoGUI, this thread should provide a pointer towards its innocence.
