### ISSUE TITLE
Adding font icons

### ISSUE THREAD

**Issue by jalva304** [wjakob/nanogui#157]
How would you go about adding or changing the icons codes in entypo.h? Were the hex values in that file generated somehow or is there some method towards getting them?

I ask because I would like to add some new entypo icons. Any help is appreciated, thanks!

**Comment by wjakob** [comment]
I think I had them from the entypo website. I processed their documentation to extract the data but unfortunately don't have the code to do that anymore. It should be fairly straightforward with a few lines of scripting code though. I'll close this ticket since it's not really a nanogui issue.
