### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by phicore** [wjakob/nanogui#16]
Do you envision using some form of bitmap caching to enhance the global perfromance, or maybe tessalation caching like in the following nanovg fork:

https://github.com/ytsedan/nanovg

I think it would help a lot

thanks

**Comment by wjakob** [comment]
Did you run into performance issues? I've found NanoVG overheads negligible in the applications I've developed so far. In any case, if it's as simple as changing the NanoVG repository link, then that should be pretty easy.
