### ISSUE TITLE
Cloning under Windows, pybind11

### ISSUE THREAD

**Issue by LeXXik** [wjakob/nanogui#164]
Hello,

Somehow I am having difficulties cloning the repo under Windows. I haven't tried on my Ubuntu.
The cloning process gets stuck on pybind11. Not sure what causing it. Am I the only one with this issue?

Alex

![clipboard01](https://cloud.githubusercontent.com/assets/5677782/19958267/d175ddfa-a1d8-11e6-861e-34470a22b1bf.jpg)

**Comment by LeXXik** [comment]
The problem seems to be with updating the submodules, since all of them appears to be empty, except .git. Using git 2.10.2, so it should work fine in theory... Anyways, cloned the submodules manually. You may close the issue, if I am the only one with the problem.

**Comment by wjakob** [comment]
Probably a network issue, I c an'treproduce it on windows on my end.
