### ISSUE TITLE
CMake error with glfw_objects object

### ISSUE THREAD

**Issue by LeXXik** [wjakob/nanogui#165]
Hi,

Got an error with CMake:

    CMake Error at CMakeLists.txt:324 (add_library):
      Error evaluating generator expression:
    
        $<TARGET_OBJECTS:glfw_objects>
    
      Objects of target "glfw_objects" referenced but no such target exists.
    
    CMake Error: CMake can not determine linker language for target: nanogui

I am a CMake noob, so forgive me, if it is trivial. I couldn't find the referenced `glfw_objects` type in the cmake file. Please, advice.

**Comment by wjakob** [comment]
This is related to not doing the recursive clone. Many of these repositories are special ones that were specifically modified to be used with NanoGUI.
