### ISSUE TITLE
Widget scissoring cutting elements

### ISSUE THREAD

**Issue by fairlight1337** [wjakob/nanogui#168]
After staring at `example1` a bit more, I realized that the widget scissoring introduced earlier is making more trouble that initially thought:

![selection_088](https://cloud.githubusercontent.com/assets/1122132/20054330/c102f64a-a4dc-11e6-9c0c-673f9dd30ce0.png)
![selection_089](https://cloud.githubusercontent.com/assets/1122132/20054331/c1032de0-a4dc-11e6-8c31-47809b57c350.png)
![selection_090](https://cloud.githubusercontent.com/assets/1122132/20054329/c103018a-a4dc-11e6-87a5-3f184a96810f.png)

The image view and the popup widget both are cut off (and there might be more), because they draw outside of their designated areas. Both could be resolved by appropriately drawing inside the bounds, and in case of the popup, moving it and drawing the background and contents with an offset to the right (or left, wherever the popup arrow is).

Right now I'm just raising attention about this, as I'm on a pretty tight schedule; I'll see after wringing out some time to fix those.

**Comment by wjakob** [comment]
I noticed this as well. I pushed out a bunch of changes that should hopefully fix everything.

Best,
Wenzel

**Comment by fairlight1337** [comment]
Oh, I see - haven't seen those yet. Thanks.

Jan
