### ISSUE TITLE
GLFrameBuffer::blit() crash after minimize window on windows using Intel Graphics.

### ISSUE THREAD

**Issue by saedrna** [wjakob/nanogui#177]
Description:

Draw contents to framebuffer object and then blit to screen. However, when minimizing the window the blit function went into problem ```0x00007FFC7F41A516 (ig9icd64.dll)``` at ```glBlitFramebuffer```.

Furthermore, if I manually set program to use Nvidia GPU, in the NVidia settings, the program runs fine.

Platform:

Visual Studio 2015, Windows 10 x64, Intel Graphics.

Steps to reproduce:

I can reproduce this problem, by changing example1.cpp

```
 virtual void drawContents() {
        using namespace nanogui;
        mFBO.bind();
        /* Draw the window contents using OpenGL */
        mShader.bind();

        glClearColor(mBackground[0], mBackground[1], mBackground[2], 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

        Matrix4f mvp;
        mvp.setIdentity();
        mvp.topLeftCorner<3,3>() = Matrix3f(Eigen::AngleAxisf((float) glfwGetTime(),  Vector3f::UnitZ())) * 0.25f;

        mvp.row(0) *= (float) mSize.y() / (float) mSize.x();

        mShader.setUniform("modelViewProj", mvp);

        /* Draw 2 triangles starting at index 0 */
        mShader.drawIndexed(GL_TRIANGLES, 0, 2);

        mFBO.release();
        mFBO.blit();
    }
    bool resizeEvent(const Eigen::Vector2i &) {
        if (mFBO.ready())
        {
            mFBO.free();
        }
        mFBO.init(mFBSize, 1);
        return true;
    }

    ...

    nanogui::GLFramebuffer mFBO;

```

**Comment by wjakob** [comment]
Having had some (terrible) experiences with Intel cards, my default assumption is that it's a graphics driver bug. (Unless you can pinpoint it to a specific nanogui issue of course)
