### ISSUE TITLE
Allow images to scale up to the size of ImageView

### ISSUE THREAD

**Issue by mrzv** [wjakob/nanogui#18]
Currently, if the size of `ImageView` is larger than the image, the image will be shown at its native (smaller) size. It would be nice to (maybe, optionally) remove this restriction. The actual change to the code of `ImageView::draw` requires removing (or rather adjusting a little) the checks for `s.x() < w` or `s.y() < h`.

**Comment by wjakob** [comment]
Hi Dmitriy,

sounds good, and seems like you already made the change on your end -- do you want to submit a pull request or attach a patch?

Regarding naming, I would suggest to have an enumeration

```
class ImageView : public ... {
    enum class SizePolicy {
       Fixed,
       Expand
   };
};
```
or something like that (with a setters and getter).

Thanks,
Wenzel

**Comment by mrzv** [comment]
Done, I think.
