### ISSUE TITLE
Nested AdvancedGridLayout does not layout correctly

### ISSUE THREAD

**Issue by omochi** [wjakob/nanogui#181]
Nested AdvancedGridLayout does not layout correctly.

I faced problem with such layout below.

```
layout1 (vertical) {
  fixed area,
  expanding area {
     layout2 (horizontal) {
        fixed area,
        expanding area {}
     }
  }
}
```

with this layout, when user resizing window (this is Screen::resizeEvent in nanogui),
if resizing expands window, it layout correctly.
But if resizing shrink window, layout does not change.

I put detailed reproducible code.
Please replace example1 app with this.

```
ExampleApplication() : nanogui::Screen(Eigen::Vector2i(1024, 768), "NanoGUI Test") {
    using namespace nanogui;

    AdvancedGridLayout * layout = new AdvancedGridLayout();
    this->setLayout(layout);
    
    layout->appendRow(100, 0);
    layout->appendRow(0, 1);
    layout->appendCol(0, 1);

    Button * b1 = new Button(this, "b1");
    layout->setAnchor(b1, AdvancedGridLayout::Anchor(0, 0));

    Widget * panel = new Widget(this);
    layout->setAnchor(panel, AdvancedGridLayout::Anchor(0, 1));

    AdvancedGridLayout * layout2 = new AdvancedGridLayout();
    panel->setLayout(layout2);

    layout2->appendCol(100, 0);
    layout2->appendCol(0, 1);
    layout2->appendRow(0, 1);

    Button * b2 = new Button(panel, "b2");
    layout2->setAnchor(b2, AdvancedGridLayout::Anchor(0, 0));

    Button * b3 = new Button(panel, "b3");
    layout2->setAnchor(b3, AdvancedGridLayout::Anchor(1, 0));

    performLayout();
}

virtual bool resizeEvent(const Eigen::Vector2i & size) { 
    performLayout();
    return false; 
}
```

I investigated the reason of this.
And I found those logic design.

1. AdvancedGridLayout expect child view to return minimum size from `preferredSize`.
https://github.com/wjakob/nanogui/blob/81871a8044da20fb0fbd856f19bc33d032a842a3/src/layout.cpp#L445
He corrects all children minimum sizes and get sum of this.
He reduce it from his area.
He split reminder area for stretching cells.
https://github.com/wjakob/nanogui/blob/81871a8044da20fb0fbd856f19bc33d032a842a3/src/layout.cpp#L482

2. AdvancedGridLayout returns current his size as `preferredSize`.
https://github.com/wjakob/nanogui/blob/81871a8044da20fb0fbd856f19bc33d032a842a3/src/layout.cpp#L353-L357

In result, outer layout expect inner layout to return minimum size,
but inner layout actually returns current size which is already expanded by logic of himself.
So outer layout can not get free area to stretch liquid cells.

Strangely, code comment write that it returns minimum size.
https://github.com/wjakob/nanogui/blob/81871a8044da20fb0fbd856f19bc33d032a842a3/src/layout.cpp#L351

I think that this is bug and not specification of AdvancedGridLayout.
Would you fix it?

**Comment by omochi** [comment]
I found more simply case.

```
		AdvancedGridLayout * layout = new AdvancedGridLayout();
		this->setLayout(layout);
		
		layout->appendRow(0, 1);
		layout->appendRow(100, 0);
		layout->appendCol(0, 1);

		Widget * w1 = new Widget(this);
		layout->setAnchor(w1, AdvancedGridLayout::Anchor(0, 0));

		Button * b1 = new Button(this, "b1");
		layout->setAnchor(b1, AdvancedGridLayout::Anchor(0, 1));
```

It can not be resized correctly.
If you remove `w1`, you can resize correctly.

The reason is same. `Widget` returns current size as `prefferedSize`.

**Comment by wjakob** [comment]
Dear @omochi,

this kind of advanced resizing is simply something that hasn't been done with this library so far. Patches and fixes are welcomed. Unfortunately, I don't have a lot of cycles these days to debug this myself.

Wenzel

**Comment by omochi** [comment]
@wjakob Okey, thanks.
I understood current status.

Layout system is complex and connected many design detail each other.
This issue is a just one sight.
I might able to fix only this issue, but I don't know that its good approach with whole widely design.
So I close this issue this time.
