### ISSUE TITLE
[minor] installed sample executables are not usable

### ISSUE THREAD

**Issue by svenevs** [wjakob/nanogui#187]
Two parts, one easy, one not sure if it's worth worrying about.  Happy to submit a PR with what you would like changed, if anything.

### The example1 program relies on resources/icons

This is easy to fix, you can just add
```
if (NANOGUI_INSTALL)
     install(TARGETS example1 example2 example3 example4
             RUNTIME DESTINATION bin)
+    install(DIRECTORY "${CMAKE_SOURCE_DIR}/resources/icons"
+            DESTINATION "${CMAKE_INSTALL_PREFIX}/bin"
+            FILES_MATCHING PATTERN "*.png")
   endif()
```
the question being, is it presumptuous to place some random `icons` directory in what will likely be a `bin` directory they are installing other things in?

Perhaps it is better to just not install `example1`?

### Questionable treatment of RPATH

I think it is generally safe to assume that somebody using `make install` will ultimately be adding the `${CMAKE_INSTALL_PREFIX}/lib` to their `LD_LIBRARY_PATH` (or Windows equivalent?).  However, if they do not then the executables cannot run when build as a shared library.

One solution for making the examples self-contained would be to change their RPATH.  So something like
```
if (NANOGUI_INSTALL)
+    if(NANOGUI_BUILD_SHARED)
+        set_target_properties(example1 example2 example3 example4
+                              PROPERTIES INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
+    endif()
     install(TARGETS example1 example2 example3 example4
             RUNTIME DESTINATION bin)
   endif()
```
of course this immediately invalidates the no `icons/*` dilemma if those got installed to `bin`, making a stronger argument for not installing `example1`.

### Quasi-related

1. If proper treatment of `bin/` is desired, should the targets be renamed to have maybe `nanoguiExample*`?
2. If a user only added the install location to `PYTHONPATH` and not `LD_LIBRARY_PATH`, with out setting `RPATH` for the python lib it will produce
```
ImportError: libnanogui.so: cannot open shared object file: No such file or directory
```

**Comment by joelmo** [comment]
I think a better place for examples to be installed is something like share/doc/nanogui, if think there is no use of having examples available as commands from the shell.

**Comment by wjakob** [comment]
I think the solution is simple: let's just not install the samples. It's easy to give them a try by cloning the git repository. The CMake install mechanism is meant for deployment, which is a completely different use case.

**Comment by wjakob** [comment]
see b6bc9e661bf34aa07803dbd073773eb44b37b6e5

**Comment by svenevs** [comment]
Haha the most elegant solution of them all!  So you do not want to change the `RPATH` of the python lib when nanogui is compiled as a shared lib?

I think I've mentioned this somewhere else but when this semester (imminently...ugh) ends I am revisiting the docs.  In addition to fixing templates, I'd like to add some more specific docs wrt to Python and having a `nanogui` available for general python wear and tear (aka from an installation).

**Comment by wjakob** [comment]
I'm open to changing the RPATH, it just seemed like installing the examples wasn't particularly helpful. Thank you very much for your help with the documentation!

**Comment by svenevs** [comment]
Huh. Nevermind?  The RPATH is somehow getting set even though the only handling of RPATH is `APPLE` specific.  I think this is related to linking using generator expressions, but it works so I'm not going to submit anything for it...
