### ISSUE TITLE
Table widget

### ISSUE THREAD

**Issue by joelmo** [wjakob/nanogui#188]
I am trying to create a table widget, this can also be used for making a list. The widget should draw it's children with alternating background color (draw rectangle first then draw child on top). I need to get the area from the layout engine. This is my attempt but does not look right, suggestions?

Is it possible to make this work for any layout applied to List?

https://gist.github.com/joelmo/36794d748b4ced428efde205b5fea72b

![image](https://cloud.githubusercontent.com/assets/336631/21096418/20b0c448-c060-11e6-856c-44ed4be021ed.png)

**Comment by wjakob** [comment]
Hi @joelmo,

It's awesome that you are designing your own widgets, but please realize that you'll be on your own (unfortunately we just don't have the resources to provide this level of support here.)

Wenzel
