### ISSUE TITLE
Screen should setSize() in constructor

### ISSUE THREAD

**Issue by mrzv** [wjakob/nanogui#189]
`Screen` should call `Widget::setSize()` in the constructor and `resizeCallbackEvent()`. Currently it goes uninitialized until the user sets it explicitly via `Screen::setSize()`.

**Comment by mrzv** [comment]
In `resizeCallbackEvent` `mSize` does get set. So it's only the constructor.

**Comment by svenevs** [comment]
Are you talking about the empty constructor?  The constructor that takes in all of the arguments / creates glfw etc does this for you indirectly.

1. Either full screen window or [`size`](https://github.com/wjakob/nanogui/blob/master/src/screen.cpp#L131) are requested.
2. Then at the end [`initialize`](https://github.com/wjakob/nanogui/blob/master/src/screen.cpp#L264) records the actual size of the window.  I think it was done this way to not have to add logic wrt fullscreen or not.

**Comment by mrzv** [comment]
Hm. You are right. I need to investigate why it appears to be unset in my code.

**Comment by mrzv** [comment]
Ok, this was the case of mis-diagnosing a problem. Nothing needs to be fixed. I'm closing the pull request. Sorry.
