### ISSUE TITLE
Error  Objects of target "glfw_objects" referenced but no such target exists

### ISSUE THREAD

**Issue by swannyPeng** [wjakob/nanogui#196]
Hi,
When building by cmake in windows,there is a error produced and I do not know how to solve it. 
_-(:з」∠)-_

CMake Error at CMakeLists.txt:339 (add_library):
 Error evaluating generator expression:
    $<TARGET_OBJECTS:glfw_objects>
Objects of target "glfw_objects" referenced but no such target exists.
CMake Error: CMake can not determine linker language for target: nanogui

Swanny

**Comment by wjakob** [comment]
Perhaps an old cmake version, or not all of the dependencies were cloned recursively?

**Comment by swannyPeng** [comment]
The error has been solved :)
Thank U!
