### ISSUE TITLE
compile log

### ISSUE THREAD

**Issue by kybin** [wjakob/nanogui#20]
Thanks, compiling always raise me headache, but it was all smooth. 

I will write my process here for log.

Debian 8 (jessie)
---

```bash
apt-get install cmake

# the I run cmake CMakeLists.txt
# error encountered: The RandR library and headers were not found
apt-get install xorg-dev libglu1-mesa-dev

# re run cmake CMakeLists.txt
# error encountered: Could NOT find PythonLibs
apt-get install python-dev

cmake CMakeLists.txt

make
```

Then, run 2 example files which works great. 

Thank you for this great GUI.

**Comment by wjakob** [comment]
Hi -- I made the python dependency optional and added the note about required packages to README.md. 

THanks,
Wenzel
