### ISSUE TITLE
Embedding nanogui inside an existing window

### ISSUE THREAD

**Issue by badosu** [wjakob/nanogui#203]
I am looking at using nanogui as a UI toolkit for audio plugins, it looks really promising for this purpose.

Usually, I implement a LV2 gui of a simple amplifier[0]. However I could not find a way to embed a nanogui window inside an existing QT, GTK or X11 window.

Any pointers on how to proceed with this would be very welcome. See the fltk, gtk and qt implementations for reference [1] [2] [3].

0: https://github.com/badosu/BadAmp
1: https://github.com/badosu/BadAmp/blob/master/amp_gui_fltk.cpp
2: https://github.com/badosu/BadAmp/blob/master/amp_gui_gtk.c
3: https://github.com/badosu/BadAmp/blob/master/amp_gui_qt.cpp

I read CONTRIBUTING.rst about feature requests and bug reports. Since I could not find another suitable medium for communication I opened this issue. Feel free to respond (or not) at your free time.

**Comment by wjakob** [comment]
This has never been done with NanoGUI and is really out of scope for this bugtracker, so I fear that you are on your own.

**Comment by badosu** [comment]
Ok, thanks!
