### ISSUE TITLE
Long time to launch application

### ISSUE THREAD

**Issue by mottosso** [wjakob/nanogui#207]
I'm getting a ~5 second delay when attempting to launch any application with NanoGUI, no matter the complexity. Both in Release and Debug builds.

Here's one of the examples.

![nanogui](https://cloud.githubusercontent.com/assets/2152766/23121472/734bfaea-f758-11e6-952b-8f5365240836.gif)

Just wondering whether this is expected, and if there's any way of slimming this down? What is it that could be taking so long?

I'm on Windows 10 x64, built NanoGUI like this.

```bash
$ cd nanogui
$ mkdir build
$ cd build
$ cmake -G "Visual Studio 14" ..
$ cmake --build . --config Release
```

Note that I'm building in 32-bit mode, as 64-bit threw an error (best saved for another issue) even though I read 32-bit mode [wasn't supported](https://nanogui.readthedocs.io/en/latest/compilation.html#compilation).

**Comment by wjakob** [comment]
This could well be some kind of penalty imposed by your OS/graphics drivers for booting up a 32 bit version of OpenGL. In any case, I highly doubt that NanoGUI would have anything to do with the delay. The 64 bit error sounds interesting, however.

**Comment by mottosso** [comment]
Thanks for the quick reply, and glad to hear that. I'll investigate on my end.

> The 64 bit error sounds interesting, however.

Making a new issue now.

**Comment by mottosso** [comment]
On a clean build, the error was no more. Could have been files from a previous build lingering, will keep an eye out.

With the 64-bit version built, the delay is still present. Any ideas on how to investigate?
