### ISSUE TITLE
Support for a multi line text box?

### ISSUE THREAD

**Issue by rcrimp** [wjakob/nanogui#209]
Is it possible to create a multiline text box, like the html5 <textarea> element?

If it's not currently possible, what's the best way to implement a large text box. I'm thinking extend the existing class TextBox, possibly?

**Comment by willdzeng** [comment]
also maybe support multi-line label?

**Comment by IGBC** [comment]
Also looking for this functionality, is anyone already working on this?

**Comment by wjakob** [comment]
Not that I know of -- contributions are definitely welcomed. I'll close the ticket since this is a feature request and not an issue with nanogui.
