### ISSUE TITLE
Serialization of Themes

### ISSUE THREAD

**Issue by xemjeff** [wjakob/nanogui#210]
I see that Widgets have code for serialization using the Serializer (core.h/ serializer.cpp).
For me, I'd like create Themes for buttons, text box styles and save them.

I could go two ways:  1) save the themes in JSON, read them and create Themes on the fly, or 2) use the serializer to save/load themes, which I think stores in binary format.

Any comments or suggestions on the best way to approach this?

**Comment by xemjeff** [comment]
A little follow-up:  When I tried to add use of the **Serializer** in example2.cpp, I get a linking error. Which is strange since these methods are both defined and _CMakeLists_ file is including _serializer/core.h_ and _src/serializer.cpp_ :

```
Undefined symbols for architecture x86_64:
  "nanogui::Serializer::Serializer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)", referenced from:
      _main in 0.o
  "nanogui::Serializer::~Serializer()", referenced from:
      _main in 0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by austensatterlee** [comment]
It might be helpful to look at a related issue: #229

**Comment by xemjeff** [comment]
Thanks @austensatterlee. I had a look at that post. That is just what I'm looking to do.
Your post brought me back to this after after a few months lingering.

Unfortunately, I can't seem to get this to build  on macOS when I use the **Serializer** class.  (See original posting at the top of this thread) The problem seems to be with linking.  The Serilaizer class symbol is not found in **libnanogui.dylib**.  I checked using 

`objdump -t libnanogui.dylib | grep -i serial`

All the other classes are there (_Button, Slider, etc_).

I also tried building with both gcc/g++ and clang/clang++. I must be missing something obvious, but this has me stumped.

Any ideas or suggestions are welcome.

**Comment by svenevs** [comment]
For the serializer approach, since everything related to serializing is templated, I think you are just missing an explicit instantiation of the `nanogui::detail::serialization_helper< Theme >`?

It all happens [in `serialization/core.h`](https://github.com/wjakob/nanogui/blob/master/include/nanogui/serializer/core.h).

**Comment by xemjeff** [comment]
I admit my ignorance here - I know little (nothing?) about template helper functions and how to use them in serialization.  From your post @svenevs , I see that I need instantiate a helper:

`nanogui::detail::serialization_helper< Theme >  serialThemeHelper`

But how to I access the **Serializer** itself to pass to the _Buttons::save(Serializer &s)_ function in the snippet below?

Can you provide with an example in a few lines?

Example : suppose I want to serialize my configuration of a button:

```
Button* button3 = gui->addButton("Stroke", []() { std::cout << "Stroke button pressed." << std::endl; });
button3->setFontSize(40);
button3->setSize(Vector2i(500,70));
button3->setFixedSize(Vector2i(500,70));
button3->setHeight(70);
button3->setBackgroundColor(Color(0.3f,0.2f,0.8f, 1.0f));
button3->save(ser);
```
btw: I think one of the examples (1..4) could include the user of the templated Serializer. It would be helpful to people like me.

**Comment by svenevs** [comment]
@xemjeff I think I finally got to the bottom of this.  I was hitting the same linking issues as you, I think it's because of how `libc++` and `libc++-abi` are getting thrown in.  It's unclear what the actual problem is, I literally commented out [all of this](https://github.com/wjakob/nanogui/blob/f9c395152f81986b2352c8353c37a9fd33e2457e/CMakeLists.txt#L127-L192) and was able to use the serializer on OSX.  It may have something to do with the frustrating `-rdynamic -Wl` nonsense, but I really don't know.

As for the other question, yes.  Right now there is no explicit `Theme` based serializer helper, so you'd need to implement that.  Examples of how the other classes got done are in `nanogui/serializer/core.h`.

**Comment by svenevs** [comment]
@xemjeff With #313 and the (now obvious) addition of `NANOGUI_EXPORT` to `class Serializer`, the symbols should now exist.  This would enable you to now serialize themes.  So here are some thoughts on approaching it

1. The `theme` class mostly consists of integers and colors, both of which are ready to be serialized.  AKA the `serialization_helper` is already specialized for these:

    https://github.com/wjakob/nanogui/blob/3a2dece3ccbc172389e65d8a3e1b1f9a38ee698d/include/nanogui/serializer/core.h#L326-L327

    meaning that you could just implement a `save` and `load` function for `nanogui::Theme`.

2. Another way to approach it would be to add another specialization, `template <> struct serialization_helper<Theme> { /* ... */ };`.  You need to implement `type_id`, `write`, and `read`.  This would then *somehow* be coupled with the `Widget` specialization (in the same file at the bottom), where the `Widget` specialization now also does theme setting using this new `Theme` helper?

3. This is where things get complicated.  For the most part, if you never explicitly create a new `nanogui::Theme` (or derived object), I believe that only **one** is ever instantiated.  When a `Widget` is created, this happens:

    https://github.com/wjakob/nanogui/blob/3a2dece3ccbc172389e65d8a3e1b1f9a38ee698d/src/widget.cpp#L39-L45

    What's important is that this is a `nanogui::ref<Theme>`, meaning that `mTheme = theme` increases the reference count (as opposed to creating a new `Theme` instance).  So the main problem with serializing themes is how to approach it (which I don't have an answer to).

    - Serializing the Theme itself should be relatively straightforward, either by doing (2) **or** adding a `save` and `load` method to `nanogui::Theme`.
    - What is difficult (and may not be possible in the current setup) is avoiding serializing the same theme object for every `Widget`.  I don't know how much of a concern that is, but the idea is that doing this does not restore the original relationship.  Suppose you made three widgets

        ```cpp
        auto *one = new Window(this, "title);
        auto *two = new Label(one, "value");
        auto *three = new Label(one, "value");
        ```

        All of `one`, `two`, and `three` now share a reference to the same `nanogui::Theme` object, since the `Theme` reference is propagated to children.  If you serialize the theme with every `Widget` (the approach for (2)), then when save and then load, you would now have three separate instances of `Theme`.  AKA the act of serialization no longer acts as a 1:1 mapping.

One possible solution is to place the burden of theme setting on the user.  You could create a serializer, `push` a "namespace" to the serializer first and serialize the custom theme.  If all instances are sharing this custom theme, it just means that you `load` the custom theme first.  Then load all other objects from the serializer, and `setTheme` on the root child (likely the `nanogui::Screen` instance).  This then gets sent to all children.  It becomes a lot more convoluted, though, when you have different themes mapping to different widgets.  In this instance, maybe an additional hashing interface of some sort could be used?

I hope that makes sense and possibly clarifies the challenge here.  I'm not really sure how to approach this one anymore :/
