### ISSUE TITLE
Asia character not support in widgets?

### ISSUE THREAD

**Issue by bo-wu** [wjakob/nanogui#214]
NanoGui is a nice looking GUI library. But it seems that Asia characters, e.g. Chinese, are not supported on the widgets. Is there any way that I can display these characters on the widgets?

**Comment by wjakob** [comment]
If you look through the forks, you should find a Japanese one. Everything is UTF-8, so really all that is needed is to switch out the fonts with ones that have CJK symbols.

**Comment by kevue2627** [comment]
@wjakob I'm sorry about that i can't find the right way input Asia characters, and what the name of the Japanese

**Comment by kevue2627** [comment]
@bo-wu hi, did you solve this problem?

**Comment by bo-wu** [comment]
> @bo-wu hi, did you solve this problem?

@kaiwuhuang Sorry, I forgot since quite long time. It seems the repository is not active for some time.
You may look around for other active gui libraries, for example Dear ImGui

**Comment by bo-wu** [comment]
> @bo-wu hi, did you solve this problem?

@kaiwuhuang Sorry, I forgot since quite long time. You can try what the author says above. What you need to do is just add one font which contains CJK symbols  in the program.
