### ISSUE TITLE
use NanoGui with native handles ( in Cinder )

### ISSUE THREAD

**Issue by q-depot** [wjakob/nanogui#219]
Hi,

I'm trying to use nanogui with Cinder, at the moment I can run the app and render the gui in a separate window(not the main app's window).
Cinder has its own native window handle and context, I can't figure out how to initialise the Screen object using the native handle, at the moment I'm working on Windows so that would be an instance of HWND.

is this possible at all?

**Comment by wjakob** [comment]
Sorry, unfortunately we can't support the Cinder interface here (not familiar with it). If you have a pure NanoGUI question, then that is a different matter of course.

**Comment by q-depot** [comment]
the question is, how do I use NanoGui with a native window handle?

**Comment by svenevs** [comment]
Hey @q-depot so the thought occurred to me, are you able to go in the opposite direction?  NanoGUI uses `glfw` to get the windows.  It doesn't really look like you can get `glfw` to accept an already created HWND handle, but you [can get the native handle from `glfw`](http://www.glfw.org/docs/latest/group__native.html).  So if Cinder allows you to wrap things, then what you could do is

1. Create a fork of NanoGUI.  To get things started, before making it "robust" / candidate to merge with upstream, just see if you can get things working for windows.
    - Just before [this line](https://github.com/wjakob/nanogui/blob/c0334597bbd7986ec980ff90476c950cd8bb5299/include/nanogui/opengl.h#L34), `#define GLFW_EXPOSE_NATIVE_WIN32` and then after including `glfw` include the native.  So it would look something like

       ```cpp
       #define GLFW_EXPOSE_NATIVE_WIN32
       #include <GLFW/glfw3.h>
       #include <GLFW/glfw3native.h>
       ```

       You may need to change the include order but I think that is correct.

    - In the `nanogui::Screen` class, create a simple pass-through function to get the HWND out.

       ```cpp
       // I don't know the API, it seems like HWND is already a pointer type
       // GLFW returns HWND not HWND*
       HWND nativeGlfwWindow() { return glfwGetWin32Window(mGLFWWindow); }
       ```
2. Create your `nanogui::Screen` like normal _before_ doing stuff with Cinder, extract the `HWND` from the `nanogui::Screen` instance, and then let Cinder wrap around that?

Of course, this assumes that Cinder will let you do such a thing.  I took a brief look around the [`GLFWWindow` class](http://www.glfw.org/docs/latest/window_guide.html#window_object), it doesn't really seem like they support passing native pointers to create a window -- only letting you get a native pointer out.  In all honesty, I'd be surprised if they had this functionality because it would somewhat defeat the purpose of using GLFW to manage window creation / destruction in the first place.

Hope that helps some!  If it works out, there might be a way to support this here (assuming @wjakob wants it), I remember a while ago somebody else trying to get NanoGUI and Cinder to play together.  I'm envisioning some simple conditional compilation, Windows and OSX have a clear choice, the question would be what to do about Linux (`X11` or `WAYLAND`), as well as what is `MIR`?

If things work out for you I may be able to help put this together more formally :smile:

**Comment by wjakob** [comment]
It's not supported -- you will have to add this yourself.

**Comment by svenevs** [comment]
Ooof. So it goes...

**Comment by wjakob** [comment]
Aha -- that actually sounds feasible. I was thinking of the other way -- getting NanoGUI to draw into an existing handle, which sounded really painful.

**Comment by q-depot** [comment]
I tried to remove all glfw references from the Screen class and I almost managed to make it work, I didn't have time to finish, but I reckon that's definitely possible and not too difficult. 

Without glfw I also got rid of the mouse/key events(for now), I can easily pass them from Cinder(or whatever framework I'm using). So as long as I can set up the NanoVg context I should be able to render NanoGui to whatever window/context I'm using. The only problem I see is merely the name of the Screen class which if you strip it from the window, it no longer makes much sense.

I can see why you create your own window, but personally I would try to (optionally) keep it out of the library so it can be easily integrated in whatever framework.

I've been thinking about implementing a base class Container(or whatever you want to call it) that is just a box with a size so all other widgets can work in the same way with a parent object.
The Screen class can inherit from Container and add the window and event handlers.

**Comment by svenevs** [comment]
> I tried to remove all glfw references from the Screen class and I almost managed to make it work, I didn't have time to finish, but I reckon that's definitely possible and not too difficult.

Hmmm.  This doesn't really sound like a direction you want to go down.  If you just want the widgets, use NanoVG directly?  The entire system is pretty deeply entrenched with GLFW.

> I was thinking of the other way -- getting NanoGUI to draw into an existing handle, which sounded really painful.

More explicitly, aside from everything in `Screen`, you have

```console
$ grep -ri glfw src/
src/common.cpp:32:extern std::map<GLFWwindow *, Screen *> __nanogui_screens;
src/common.cpp:48:    glfwSetErrorCallback(
src/common.cpp:50:            if (error == GLFW_NOT_INITIALIZED)
src/common.cpp:52:            std::cerr << "GLFW error " << error << ": " << descr << std::endl;
src/common.cpp:56:    if (!glfwInit())
src/common.cpp:57:        throw std::runtime_error("Could not initialize GLFW!");
src/common.cpp:59:    glfwSetTime(0);
src/common.cpp:81:                    glfwPostEmptyEvent();
src/common.cpp:94:                } else if (glfwWindowShouldClose(screen->glfwWindow())) {
src/common.cpp:109:            glfwWaitEvents();
src/common.cpp:113:        glfwPollEvents();
src/common.cpp:132:    glfwTerminate();
src/colorwheel.cpp:146:    if (!mEnabled || button != GLFW_MOUSE_BUTTON_1)
src/textbox.cpp:286:    if (button == GLFW_MOUSE_BUTTON_1 && down && !mFocused) {
src/textbox.cpp:296:            double time = glfwGetTime();
src/textbox.cpp:315:                double time = glfwGetTime();
src/textbox.cpp:403:        if (action == GLFW_PRESS || action == GLFW_REPEAT) {
src/textbox.cpp:404:            if (key == GLFW_KEY_LEFT) {
src/textbox.cpp:405:                if (modifiers == GLFW_MOD_SHIFT) {
src/textbox.cpp:414:            } else if (key == GLFW_KEY_RIGHT) {
src/textbox.cpp:415:                if (modifiers == GLFW_MOD_SHIFT) {
src/textbox.cpp:424:            } else if (key == GLFW_KEY_HOME) {
src/textbox.cpp:425:                if (modifiers == GLFW_MOD_SHIFT) {
src/textbox.cpp:433:            } else if (key == GLFW_KEY_END) {
src/textbox.cpp:434:                if (modifiers == GLFW_MOD_SHIFT) {
src/textbox.cpp:442:            } else if (key == GLFW_KEY_BACKSPACE) {
src/textbox.cpp:449:            } else if (key == GLFW_KEY_DELETE) {
src/textbox.cpp:454:            } else if (key == GLFW_KEY_ENTER) {
src/textbox.cpp:457:            } else if (key == GLFW_KEY_A && modifiers == SYSTEM_COMMAND_MOD) {
src/textbox.cpp:460:            } else if (key == GLFW_KEY_X && modifiers == SYSTEM_COMMAND_MOD) {
src/textbox.cpp:463:            } else if (key == GLFW_KEY_C && modifiers == SYSTEM_COMMAND_MOD) {
src/textbox.cpp:465:            } else if (key == GLFW_KEY_V && modifiers == SYSTEM_COMMAND_MOD) {
src/textbox.cpp:523:        glfwSetClipboardString(sc->glfwWindow(),
src/textbox.cpp:533:    const char* cbstr = glfwGetClipboardString(sc->glfwWindow());
src/textbox.cpp:564:        if (mMouseDownModifier == GLFW_MOD_SHIFT) {
src/button.cpp:55:    if (button == GLFW_MOUSE_BUTTON_1 && mEnabled) {
src/imageview.cpp:165:    if ((button & (1 << GLFW_MOUSE_BUTTON_LEFT)) != 0 && !mFixedOffset) {
src/imageview.cpp:197:        case GLFW_KEY_LEFT:
src/imageview.cpp:199:                if (GLFW_MOD_CONTROL & modifiers)
src/imageview.cpp:206:        case GLFW_KEY_RIGHT:
src/imageview.cpp:208:                if (GLFW_MOD_CONTROL & modifiers)
src/imageview.cpp:215:        case GLFW_KEY_DOWN:
src/imageview.cpp:217:                if (GLFW_MOD_CONTROL & modifiers)
src/imageview.cpp:224:        case GLFW_KEY_UP:
src/imageview.cpp:226:                if (GLFW_MOD_CONTROL & modifiers)
src/window.cpp:160:    if (mDrag && (button & (1 << GLFW_MOUSE_BUTTON_1)) != 0) {
src/window.cpp:172:    if (button == GLFW_MOUSE_BUTTON_1) {
src/widget.cpp:89:    if (button == GLFW_MOUSE_BUTTON_1 && down && !mFocused)
```

Of course you're welcome to give it a go, but it'll be quite a long road...
