### ISSUE TITLE
Cannot find SDL/SDL_opengl.h

### ISSUE THREAD

**Issue by dk1206** [wjakob/nanogui#227]
I have just opened VS 2015 with the Example1 CPP and it cannot be built due to this error:

`Cannot open source file "SDL/SDL_opengl.h"`

Any idea what I missed out?

**Comment by svenevs** [comment]
Hmm.  Are you sure you are using this repo?  I know one of the forks is an SDL port, but the main project uses GLFW and there shouldn't be any references to SDL anywhere.

If you are new to this stuff, there are many different libraries to control drawing windows with opengl.  SDL is one, GLFW is another, there's also GLUT and a lot more.  You generally have to commit to one or the other, SDL and GLFW for example are not friends and (to my knowledge) will directly conflict with each other.

If you are using this one can you give more of the error (specifically show the include traceback that ultimately led to it trying to include `SDL/SDL_opengl.h`)?
