### ISSUE TITLE
No input of floats, doubles and ints possible.

### ISSUE THREAD

**Issue by StNimmerlein** [wjakob/nanogui#25]
Hello,
the adding of variables that are not boolean seems to be broken. This can even be observed in the provided examples:
You can comile the examples (via cmake) and run them, but as soon as you click into the value field (eg. of "Floating point") the program crashes with "Caught exception in event handler: regex_error".

**Comment by wjakob** [comment]
Hi,

it's a compiler/C++ library implementation issue -- regular expressions are not implemented until in recent libstdc++ versions. See here for details: http://stackoverflow.com/questions/23474121/what-part-of-regex-is-supported-by-gcc-4-9

Best,
Wenzel
