### ISSUE TITLE
UI can't draw properly in 'release' mode

### ISSUE THREAD

**Issue by hanke100321** [wjakob/nanogui#257]
hello, i'm trying to copy the code from example3 to my existed opengl project. And in 'Debug' mode, the project works fine, but in 'Release' mode the gui can't draw properly. My OS is win10, and i'm working on visual studio 2015.
the code looks like this:
```
void main()
{
        // Init GLFW
	glfwInit();
	glfwSetTime(0);

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_SAMPLES, 0);
	glfwWindowHint(GLFW_RED_BITS, 8);
	glfwWindowHint(GLFW_GREEN_BITS, 8);
	glfwWindowHint(GLFW_BLUE_BITS, 8);
	glfwWindowHint(GLFW_ALPHA_BITS, 8);
	glfwWindowHint(GLFW_STENCIL_BITS, 8);
	glfwWindowHint(GLFW_DEPTH_BITS, 24);
	glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);

	m_pWindow = glfwCreateWindow(screenWidth, screenHeight, name.c_str(), nullptr, nullptr); 
	if (m_pWindow == nullptr) 
	{
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
	}
	glfwMakeContextCurrent(m_pWindow);	
#if defined(NANOGUI_GLAD)
	if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
		throw std::runtime_error("Could not initialize GLAD!");
	glGetError(); // pull and ignore unhandled errors like GL_INVALID_ENUM
#endif
       //nanogui
	{
		// Create a nanogui screen and pass the glfw pointer to initialize
		screen = new nanogui::Screen();
		screen->initialize(m_pWindow, true);
		nanogui::FormHelper *gui = new nanogui::FormHelper(screen);
		nanogui::ref<nanogui::Window> nanoguiWindow = gui->addWindow(Eigen::Vector2i(10, 10), "Form helper example");
		gui->addGroup("Basic types");
		gui->addVariable("bool", bvar)->setTooltip("Test tooltip.");
		gui->addVariable("string", strval);

		screen->setVisible(true);
		screen->performLayout();
		nanoguiWindow->center();
	}
       while (!glfwShouldClose(m_pWindow))
       {
               glfwPollEvents();
               glClearColor(0.2f, 0.2f, 0.2f, 1.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
		glEnable(GL_DEPTH_TEST);

		int pixelWidth, pixelHeight;
		glfwGetFramebufferSize(g_pWindow->GetGLFWWindow(), &pixelWidth, &pixelHeight);
		glViewport(0, 0, pixelWidth, pixelHeight);

                // Draw nanogui
		screen->drawContents();
		screen->drawWidgets();

                glfwSwapBuffers(m_pWindow);
       }
      glfwTerminate();
}
```

the result in 'Debug':
![nanogui-debug](https://user-images.githubusercontent.com/13730578/30192894-c3d0f328-947c-11e7-9218-236dc3b55d63.png)

the result in 'Release':
![nanogui-release](https://user-images.githubusercontent.com/13730578/30192899-cfe5bcde-947c-11e7-903d-3a17f0e6719c.png)

**Comment by svenevs** [comment]
the only thing that appears to be missing is the stuff [at the top of example3](https://github.com/wjakob/nanogui/blob/13f54b7950751443204ad390624e52498c11a126/src/example3.cpp#L14-L28).  maybe you'll get lucky and that'll fix it?

P.S. for pasting multiple lines of code use three backticks

     ```
     ... paste code here on line below
     ... close with three backticks on next line
     ```

**Comment by hanke100321** [comment]
Thank you for your reply! I tried to copy all code in example3 to my project (including the top of stuff), still in 'debug' mode it works fine. But in 'release' mode, it has a " 0xC0000005 Access Violation" when meeting this line `screen->performLayout();`
![nanogui-error](https://user-images.githubusercontent.com/13730578/30204296-822f4f38-94b7-11e7-9c3f-ec3e38b92f89.png)

**Comment by FurryFur** [comment]
I tried to run the examples in release mode and they all crash with access violation. They all work fine in debug mode.

**Comment by svenevs** [comment]
@hanke100321 see [speculation here](https://github.com/wjakob/nanogui/issues/258#issuecomment-329050061)

**Comment by svenevs** [comment]
@hanke100321 the resolution appears to be to update to Visual Studio 2017.  If you are able to do that, I advise doing so.  If you do, please report back whether or not this fixed your problem

**Comment by FurryFur** [comment]
Alternatively you can build libraries from 2017 and link them in your 2015 project, it's what I'm doing.

**Comment by hanke100321** [comment]
I see!! thank you guys : )

**Comment by aaseagrass** [comment]
Hello Everyone! Hope there is someone here who is knowledgeable in creating GUI in Python using Qt creator and Qt designer. Right now, I'm having difficulty in doing the GUI in our senior's project. I'm working with PyQt4 library for our GUI however, yesterday our uimain for our GUI suddenly didn't pop up. Instead, this kind of syntax appears everytime I run my GUI .py code "Process finished with exit code -1073741819 (0xC0000005)" and the ui didn't show up. Anyone here who knows who to solve that kind error? Thank you very much! This will be a another great help for us.

**Comment by svenevs** [comment]
@aaseagrass I think you are on the wrong repo, NanoGUI doesn't have anything to do with Qt.  Their documentation is [here](https://riverbankcomputing.com/software/pyqt/intro).

**Comment by jialiuBellus3d** [comment]
I see this issue as well when I try to build example1 in release mode. Switched from VS2015 to VS2019 and the issue is gone.
