### ISSUE TITLE
Compile errors on VS 2015, win32

### ISSUE THREAD

**Issue by Nuclearfossil** [wjakob/nanogui#26]
lots of issues with the build in VS 2015 [x86]:

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because D:/dev/nanogui/build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/dev/nanogui/build/ext_build/glfw/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because D:/dev/nanogui/build/ext_build/glfw/src/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: bin2c, Configuration: Debug Win32 ------
3>------ Rebuild All started: Project: glfw_objects, Configuration: Debug Win32 ------
4>------ Skipped Rebuild All: Project: mkdoc, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration 
2>  Building Custom Rule D:/dev/nanogui/CMakeLists.txt
2>  CMake does not need to re-run because D:\dev\nanogui\build\CMakeFiles\generate.stamp is up-to-date.
3>  Building Custom Rule D:/dev/nanogui/ext/glfw/src/CMakeLists.txt
3>  CMake does not need to re-run because D:\dev\nanogui\build\ext_build\glfw\src\CMakeFiles\generate.stamp is up-to-date.
2>  bin2c.c
3>  context.c
3>  init.c
3>  input.c
2>  bin2c.vcxproj -> D:\dev\nanogui\build\Debug\bin2c.exe
3>  monitor.c
3>  window.c
3>  win32_init.c
3>  win32_monitor.c
3>  win32_time.c
3>  win32_tls.c
3>  win32_window.c
3>  winmm_joystick.c
3>  wgl_context.c
3>  Generating Code...
3>  glfw_objects.vcxproj -> D:\dev\nanogui\build\ext_build\glfw\src\glfw_objects.dir\Debug\glfw_objects.lib
5>------ Rebuild All started: Project: nanogui, Configuration: Debug Win32 ------
6>------ Rebuild All started: Project: glfw, Configuration: Debug Win32 ------
6>  Building Custom Rule D:/dev/nanogui/ext/glfw/src/CMakeLists.txt
5>  Building Custom Rule D:/dev/nanogui/CMakeLists.txt
6>  CMake does not need to re-run because D:\dev\nanogui\build\ext_build\glfw\src\CMakeFiles\generate.stamp is up-to-date.
5>  CMake does not need to re-run because D:\dev\nanogui\build\CMakeFiles\generate.stamp is up-to-date.
5>  Running bin2c
5>  nanovg.c
6>     Creating library D:/dev/nanogui/build/ext_build/glfw/src/Debug/glfw3dll.lib and object D:/dev/nanogui/build/ext_build/glfw/src/Debug/glfw3dll.exp
6>  glfw.vcxproj -> D:\dev\nanogui\build\ext_build\glfw\src\Debug\glfw3.dll
5>  glew.c
5>  resources.cpp
5>  glutil.cpp
5>  common.cpp
5>  widget.cpp
5>  theme.cpp
5>  layout.cpp
5>  screen.cpp
5>  label.cpp
5>  window.cpp
5>D:\dev\nanogui\src\screen.cpp(213): warning C4316: 'nanogui::Theme': object allocated on the heap may not be aligned 16
5>D:\dev\nanogui\src\layout.cpp(428): warning C4018: '>': signed/unsigned mismatch
5>  popup.cpp
5>  checkbox.cpp
5>d:\dev\nanogui\src\screen.cpp(380): warning C4702: unreachable code
5>d:\dev\nanogui\src\screen.cpp(432): warning C4702: unreachable code
5>d:\dev\nanogui\src\screen.cpp(481): warning C4702: unreachable code
5>  button.cpp
5>  popupbutton.cpp
5>  combobox.cpp
5>  progressbar.cpp
5>  slider.cpp
5>  messagedialog.cpp
5>D:\dev\nanogui\src\combobox.cpp(52): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>  textbox.cpp
5>  imagepanel.cpp
5>  imageview.cpp
5>  vscrollpanel.cpp
5>  colorwheel.cpp
5>  colorpicker.cpp
5>D:\dev\nanogui\src\messagedialog.cpp(37): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
5>D:\dev\nanogui\src\messagedialog.cpp(39): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
5>D:\dev\nanogui\src\messagedialog.cpp(46): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>D:\dev\nanogui\src\messagedialog.cpp(49): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>  graph.cpp
5>D:\dev\nanogui\src\colorpicker.cpp(26): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
5>     Creating library D:/dev/nanogui/build/Debug/nanogui.lib and object D:/dev/nanogui/build/Debug/nanogui.exp
5>  nanogui.vcxproj -> D:\dev\nanogui\build\Debug\nanogui.dll
7>------ Rebuild All started: Project: example1, Configuration: Debug Win32 ------
8>------ Rebuild All started: Project: example2, Configuration: Debug Win32 ------
9>------ Rebuild All started: Project: nanogui_python, Configuration: Debug Win32 ------
7>  Building Custom Rule D:/dev/nanogui/CMakeLists.txt
8>  Building Custom Rule D:/dev/nanogui/CMakeLists.txt
8>  CMake does not need to re-run because D:\dev\nanogui\build\CMakeFiles\generate.stamp is up-to-date.
9>  Building Custom Rule D:/dev/nanogui/CMakeLists.txt
8>  example2.cpp
9>  CMake does not need to re-run because D:\dev\nanogui\build\CMakeFiles\generate.stamp is up-to-date.
9>  python.cpp
7>  CMake does not need to re-run because D:\dev\nanogui\build\CMakeFiles\generate.stamp is up-to-date.
7>  example1.cpp
8>D:\dev\nanogui\include\nanogui/formhelper.h(82): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
8>D:\dev\nanogui\include\nanogui/formhelper.h(130): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
8>D:\dev\nanogui\include\nanogui/formhelper.h(146): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
9>D:\dev\nanogui\include\nanogui/formhelper.h(82): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
9>D:\dev\nanogui\include\nanogui/formhelper.h(130): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
9>D:\dev\nanogui\include\nanogui/formhelper.h(146): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
8>D:\dev\nanogui\include\nanogui/formhelper.h(122): error C2719: 'v': formal parameter with requested alignment of 16 won't be aligned
8>  D:\dev\nanogui\src\example2.cpp(54): note: see reference to function template instantiation 'nanogui::detail::FormWidget<nanogui::Color,std::true_type> *nanogui::FormHelper::addVariable<nanogui::Color>(const std::string &,Type &,bool)' being compiled
8>          with
8>          [
8>              Type=nanogui::Color
8>          ]
8>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(272): error C2719: '<_Args_0>': formal parameter with requested alignment of 16 won't be aligned
8>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(464): note: see reference to class template instantiation 'std::_Func_class<_Ret,Type>' being compiled
8>          with
8>          [
8>              _Ret=void,
8>              Type=nanogui::Color
8>          ]
8>  D:\dev\nanogui\include\nanogui/formhelper.h(125): note: see reference to class template instantiation 'std::function<void (Type)>' being compiled
8>          with
8>          [
8>              Type=nanogui::Color
8>          ]
9>D:\dev\nanogui\python\python.cpp(650): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 16 won't be aligned
7>D:\dev\nanogui\src\example1.cpp(54): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(56): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(58): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(62): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(63): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(67): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(68): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(70): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(73): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(78): warning C4316: 'nanogui::ToolButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(79): warning C4316: 'nanogui::ToolButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(80): warning C4316: 'nanogui::ToolButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(81): warning C4316: 'nanogui::ToolButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(83): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(84): warning C4316: 'nanogui::PopupButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(87): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(89): warning C4316: 'nanogui::PopupButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(98): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(102): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(107): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(112): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(121): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(122): warning C4316: 'nanogui::PopupButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(146): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(150): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(155): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(161): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(162): warning C4316: 'nanogui::ComboBox': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(163): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(171): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(174): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(180): warning C4316: 'nanogui::Slider': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(201): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(203): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(204): warning C4316: 'nanogui::Graph': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(224): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(236): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(248): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(255): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(257): warning C4316: 'nanogui::ComboBox': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(261): warning C4316: 'nanogui::Label': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(262): warning C4316: 'nanogui::PopupButton': object allocated on the heap may not be aligned 16
7>D:\dev\nanogui\src\example1.cpp(272): warning C4316: 'nanogui::Button': object allocated on the heap may not be aligned 16
7>  example1.vcxproj -> D:\dev\nanogui\build\Debug\example1.exe
10>------ Skipped Rebuild All: Project: ALL_BUILD, Configuration: Debug Win32 ------
10>Project not selected to build for this solution configuration 
========== Rebuild All: 6 succeeded, 2 failed, 2 skipped ==========

**Comment by Nuclearfossil** [comment]
Apparently the library only supports Win64 as the platform?  Switched to that build config:

  cmake -G "Visual Studio 14 2015 Win64" .

and we compile fine. However building via

  cmake -G "Visual Studio 14 2015" .

produces the above error. Did I miss this in the documentation?

**Comment by phicore** [comment]
I build it under win32. You need to set alignement to 16bytes un the cmake generated solution

**Comment by wjakob** [comment]
@phicore: can you provide details how to do this? Perhaps it could be integrated into the default build file?

**Comment by wjakob** [comment]
never mind, fixed in fe1e8fdf384cf27d3ffe040a48c8238d848d8312

**Comment by dmazzella** [comment]
Hi,
i have problem on build in windows 10 - vs2015 Win32.

command to generate:
cmake -G "Visual Studio 14 2015"  

Error	C2719	'v': formal parameter with requested alignment of 16 won't be aligned	example2	C:\msys64\home\dma\projects\nanogui\include\nanogui\formhelper.h	122	
Error	C2719	'unnamed-parameter': formal parameter with requested alignment of 16 won't be aligned	nanogui_python	C:\msys64\home\dma\projects\nanogui\python\python.cpp	886	
Error	C2719	'<_Args_0>': formal parameter with requested alignment of 16 won't be aligned	example2	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional	276	

any suggestion?

another problem on python/example1.py.
***************
*** 17,23 ****
  from nanogui import Color, Screen, Window, GroupLayout, BoxLayout, \
                      ToolButton, Vector2i, Label, Button, Widget, \
                      PopupButton, CheckBox, MessageDialog, VScrollPanel, \
!                     ImagePanel, ImageView, IntBox, ComboBox, ProgressBar, Slider, \
                      TextBox, ColorWheel, Graph, VectorXf, GridLayout, \
                      Alignment, Orientation, TabWidget
  
--- 17,23 ----
  from nanogui import Color, Screen, Window, GroupLayout, BoxLayout, \
                      ToolButton, Vector2i, Label, Button, Widget, \
                      PopupButton, CheckBox, MessageDialog, VScrollPanel, \
!                     ImagePanel, ImageView, ComboBox, ProgressBar, Slider, \
                      TextBox, ColorWheel, Graph, VectorXf, GridLayout, \
                      Alignment, Orientation, TabWidget
  
missing "IntBox"

Ragards.
D.
