### ISSUE TITLE
How does it work with Mobile framework?

### ISSUE THREAD

**Issue by Taymindis** [wjakob/nanogui#268]
I am currently using oxygine2d game engine to work with NanoVg by using this tutorial
[https://github.com/oxygine/oxygine-framework/wiki/nanovg](url)
 everything looks fine. I wonder how does it work  NANOGui

**Comment by wjakob** [comment]
Sorry, this is not a usable issue report. Please take a look at the supplied examples and ask a specific question if you run in to issues.
