### ISSUE TITLE
Compilation with TDM-GCC under windows

### ISSUE THREAD

**Issue by phicore** [wjakob/nanogui#27]
It can be done but the **CMakelists.txt** must be sligthly updated

First WIN32 must be defined explicitely by adding:

```
if(WIN32)
	add_definitions ("-DWIN32")
endif()
```

and also adding -std=c++11 in case we are not using MSVC

```
if(MSVC)
  if(CMAKE_CXX_FLAGS MATCHES "/W[0-4]")
    string(REGEX REPLACE "/W[0-4]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4")
  endif()
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -std=c++11")
endif()
```

Beside this nanogui works out of the box with the current TDM (tdm64-gcc-5.1.0-2.exe)

**Comment by wjakob** [comment]
Hi,

I decided to make a different set of changes. Can you check if you can compile the latest version out of the box?

Thanks,
Wenzel

**Comment by phicore** [comment]
Hi, 

Your last changes have the benefit of creating the library and the both examples out of the box without tweaking the CMakelists.txt.

But unfortunately the executables are not working anymore:

![image](https://cloud.githubusercontent.com/assets/6534441/11453546/9c0bff94-960f-11e5-8e2b-2c5ed9c4d5c2.png)

During the link phase i saw something new about LTO items

![image](https://cloud.githubusercontent.com/assets/6534441/11453557/3ab5a3ca-9610-11e5-9325-ff24f66c2f4e.png)

maybe it is linked to the problem


I made the counterproof by just using my CMakeLists.txt again instead of the last committed one and I could regenerate working apps again.

Best regards

**Comment by phicore** [comment]
The TDM-GCC readme file indicates:

```
Every TDM-GCC release since 4.5.1 includes support for GCC's Link-Time
Optimizer. As long as GCC's own drivers (gcc, g++, etc.) are used at both
compile-time and link-time, and the "-flto" option is specified at both compile-
time and link-time, link-time optimization will be applied. See
<http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html> for further details.
```


So maybe we have to check if LTO is defined at compile time also and not only at link time

Best regards

**Comment by wjakob** [comment]
ok, another attempt. I tried to add some code that tries to autodetect if -flto is supported in the first place.

Can you check if you're able to compile the latest nanogui out of the box?

**Comment by wjakob** [comment]
I committed this in cee7e0307866cf4897f5eb9f1aece3aba0b51630 -- please check that version.

**Comment by phicore** [comment]
It works perfectly now out of the box. 
Thanks for supporting a now even larger set of the platforms out there.

**Comment by wjakob** [comment]
Great, thanks. I am closing this ticket then.
