### ISSUE TITLE
Multiple CPP files #define STB_IMAGE_IMPLEMENTATION

### ISSUE THREAD

**Issue by Gibgezr** [wjakob/nanogui#274]
I couldn't get NanoGUI to build the examples in VS2017, and it was because nanovg.c already had the line:
#define STB_IMAGE_IMPLEMENTATION
...in it, but each example also tried to define it as well. The stb_image.h documentation clearly states that only ONE source file should define the implementation. If you comment out that line in the examples they link just fine.

**Comment by nzod** [comment]
Thanks! Getting rid of the defines indeed works.

**Comment by svenevs** [comment]
Closing as duplicate of #179 which should have an official solution soon.  This has had low priority as it only affects building the demo application and static libraries with windows.
