### ISSUE TITLE
ImageView for 2D array

### ISSUE THREAD

**Issue by fwsGonzo** [wjakob/nanogui#277]
I was trying to send a custom shader and TEXTURE_2D_ARRAY image to ImageView, but after reading the code I can see that it will never work unless the ImageView is refactored a bit, or another widget, say, Image2DArray is added.

I'm going the new widget route. Just letting you know! :)
Awesome library btw

I can see that it may be possible to just add another parameter to imageview detailing the texture type, and and further changes should be fairly minimal

The dream would be to have a widget that could store an X*Y array of tile IDs, then draw each tile in a X*Y grid from a TEXTURE_2D_ARRAY, with or without borders between tiles.

**Comment by fwsGonzo** [comment]
I've been working on this tile grid view for a while now, and I'm kind of on the fence about how useful it would be for everyone else. It's kinda nice to just send a vector of tile IDs and then get a border around every tile inside the container with working zoom and offset.

If someone needs this functionality just message me, one way or another.

**Comment by svenevs** [comment]
@fwsGonzo sound interesting, though I don't think I really understand the use-case.  Maybe just create a [gist](https://gist.github.com/) and link it here?  I'd be interested in taking a look, it might suit the needs of something I once wanted to do but didn't care enough to implement :wink:

**Comment by fwsGonzo** [comment]
@svenevs I have found this library immensely useful, and I will definitely show you the final widget when I'm done, however it will probably not be very useful as a generic widget. Right now I'm custom-rendering each tile simply because they all have different rendering rules, so the widget is mostly just a background with tile-slots and a callback for rendering tiles. Anyways, nice GUI library! :+1: :post_office:

**Comment by svenevs** [comment]
No worries, if it turns into something more generic I can take a look / help with python bindings provided the project creator / owner desires it (clarification: it's not me!).  I'm just an enthusiastic user who has also benefited greatly from this library :scream:
