### ISSUE TITLE
The framework is good but is to much tightly coupled very hard to embed it to other application 

### ISSUE THREAD

**Issue by meiry** [wjakob/nanogui#28]
it is light and nice framework , but when trying to embed it to another application which already init glfw3 , there is need to mix the hosting app code  into Screen class ,   
this is pain , design as i see it and know should be flexible to add the framework into other .

**Comment by wjakob** [comment]
Well, this is not a very helpful bug report. The Screen class specifically has support for working with an already GLFW context.

If you don't like it, you are welcome to submit improvements.

**Comment by meiry** [comment]
Don't get me wrong , it is not bug only suggestion , 
the framework is great and very well written  but it is very hard to GUI layer and embed it .

**Comment by wjakob** [comment]
Ok, I understand. Unfortunately my resources are very limited to work on suggestions. I do, however, accept patches if they contribute useful functionality or architectural improvements. Feel free to start a new pull request.
