### ISSUE TITLE
Problems with usage

### ISSUE THREAD

**Issue by tylersweat** [wjakob/nanogui#287]
I have been trying to set up everything up so that I can use nanogui but I can't seem to get it. At first, I was getting errors that it couldn't find Eigen, but that issue has been resolved. Now I am getting errors saying that it cannot find nanovg.h. I want to get this set up for development on Windows 10 with VS 2017. I have also been trying to get it working on a virtual machine running Ubuntu 17.04 and I get the same errors on both. What am I missing and how can I get this working?

![visualstudioerror](https://user-images.githubusercontent.com/5776857/33104214-2fa0e292-cee4-11e7-83d0-8abcf814a3a1.png)
![ubuntuerror](https://user-images.githubusercontent.com/5776857/33104213-2f8ca73c-cee4-11e7-93c5-48cf409af0ec.png)

**Comment by sveencoop** [comment]
You need include get \nanogui\ext\nanovg\src on your project
