### ISSUE TITLE
example1 asks for image directory; examples 2 and 3 look the same

### ISSUE THREAD

**Issue by yurivict** [wjakob/nanogui#296]
```
$ ./example1 
Caught a fatal error: Could not open image directory!
```
It should at least say what directory does it want.

----

examples 2 and 3 look the same, is this a mistake?

**Comment by svenevs** [comment]
See #273, this is why the examples are not installed -- it's assumed you are building out of source and running from a specific directory ("the" build directory).

**Comment by yurivict** [comment]
Ok, thanks!
