### ISSUE TITLE
Resize windows

### ISSUE THREAD

**Issue by mrzv** [wjakob/nanogui#3]
It would be great to have the ability to resize windows (by dragging a corner with a mouse, or something like that).

**Comment by wjakob** [comment]
I don't need it for any of my projects right now -- but I would definitely consider a patch if this is something you'd like to work on.

**Comment by mrzv** [comment]
I don't think I've grokked the design enough to do this yet. But if I do, I'll add it.

**Comment by wjakob** [comment]
The latest repository version now has a resizing-aware ``AdvancedGridLayout`` so that exposing resizable windows is just a technicality at this point.

**Comment by wjakob** [comment]
(Closing -- see the ongoing PR #146.)
