### ISSUE TITLE
Screen::initialize throwing runtime error: Could not initialize GLAD! [C++]

### ISSUE THREAD

**Issue by sveencoop** [wjakob/nanogui#307]
I already have a project in GLFW where I use "#pragma once" always, so I can not use "#if def"

I have already initialized GLAD in the beginning but when i call Screen::initialize i get "Runtime error: Could not initialize GLAD!"

```
#pragma once

#include <glad\glad.h>
#include <GLFW\glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp> 
#include <nanogui.h>

main(){
 ...
        window = glfwCreateWindow(width, height, title, NULL, NULL);
...
	if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
		std::cout << "Failed to initialize GLAD" << std::endl;
		return false;
	}

        openglWindow::nanoscreen = new Screen();
	try {
		nanoscreen->initialize(window, true);
	}
	catch (std::runtime_error& e) {
		std::cout << "Runtime Error: " << e.what() << std::endl;
	}
}
```

**Comment by svenevs** [comment]
double check what you are doing with example 3, there's nothing that pops out in the above.  particularly, i think this line needs to happen after you make the window but before loading glad:

https://github.com/wjakob/nanogui/blob/f61c407ea4cb336aefcdd82202c6e09ff21b9e79/src/example3.cpp#L80

Note also that example3 is only including / loading / initializing glad when `NANOGUI_GLAD` is defined.  This is always set to `ON` when building under Windows, but if `NANOGUI_GLAD` was not defined then glad is not built (it would result in linking errors on a Unix system).

**Comment by sveencoop** [comment]
I was able to fix the problem of "#if def" and "#pragma once", but still continue to issue "Could not initialize GLAD"

The call order is correct, same as the tutorial


```
bool openglWindow::newWindow(char const *title, int width, int height, bool fullscreen) {
	GLFWwindow* window;
	if (fullscreen) { //fullscreen mode
		GLFWmonitor* monitor = glfwGetPrimaryMonitor();
		const GLFWvidmode* mode = glfwGetVideoMode(monitor);
		glfwWindowHint(GLFW_RED_BITS, mode->redBits);
		glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
		glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
		glfwWindowHint(GLFW_REFRESH_RATE, mode->refreshRate);
		window = glfwCreateWindow(mode->width, mode->height, title, monitor, NULL);
		width = mode->width;
		height = mode->height;
	}
	else { //windowed mode
		window = glfwCreateWindow(width, height, title, NULL, NULL);
	}

	if (window == NULL) {
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
		return false;
	}

	glfwMakeContextCurrent(window);

	#if defined(NANOGUI_GLAD)
		if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
			throw std::runtime_error("Could not initialize GLAD!");
		glGetError(); // pull and ignore unhandled errors like GL_INVALID_ENUM
	#endif
	
	glClearColor(0.2f, 0.25f, 0.3f, 1.0f);
	glClear(GL_COLOR_BUFFER_BIT);

	openglWindow::nanoscreen = new Screen();
	try {
		nanoscreen->initialize(window, true);
	}
	catch (std::runtime_error& e) {
		std::cout << "Runtime Error: " << e.what() << std::endl;
	}

	glfwSetFramebufferSizeCallback(window, openglWindow::framebuffer_size_callback);
	openglWindow::window = window;
	openglWindow::w_width = width;
	openglWindow::w_height = height;
	openglWindow::w_ratio = ((float)width) / ((float)height);
	openglWindow::initEventListeners();
	return true;
}
```

**Comment by sveencoop** [comment]
I'm working with GLAD for Opengl 4.3

**Comment by svenevs** [comment]
Ohhhhhhh.  Try 3.3 if you can do that easily:

https://github.com/wjakob/nanogui/blob/cf576ee1ed53155a9abf356291eb0030dc2f7b3c/ext/glad/src/glad.c#L3-L16

That's the latest the NanoGUI GLAD supports right now.  It's generated using that website.  Maybe it would be time to update to 4.6?

http://glad.dav1d.de/#profile=core&language=c&specification=gl&api=gl%3D4.6

Try replacing the contents of `ext/glad` with that.

**Comment by sveencoop** [comment]
Try to compile in CMAKE with Glad 4.3, did not work.
gladLoadGLLoader((GLADloadproc)glfwGetProcAddress) on **screen** always return false 

I realized that I have the same problem of this issue also open #248

**Comment by svenevs** [comment]
Does it work if you do **not** initialize GLAD before calling `Screen::initialize`?

https://github.com/wjakob/nanogui/blob/cf576ee1ed53155a9abf356291eb0030dc2f7b3c/src/screen.cpp#L43

I think we could add a `bool initializeGLAD = true` parameter, which you / anybody else calling `Screen::initialize` would set to `false`.

**Comment by sveencoop** [comment]
I used **_gladLoadGL_** instead of **_gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)_**
, and compile the nanogui again, and works fine for me.

**Comment by sveencoop** [comment]
But

> 		// Draw nanogui
> 		openglWindow::nanoscreen->drawContents();
> 		openglWindow::nanoscreen->drawWidgets();

is not drawing

**Comment by sveencoop** [comment]
No, it gives error of the first instruction that glad uses after

I tried to use **gladLoadGL()** in place of **(GLADloadproc) glfwGetProcAddress**, does not generate errors, but it also does not draw the components on the screen later.

(GLADloadproc)glfwGetProcAddress returns different addresses, I do not know why

**Comment by sveencoop** [comment]
I passed the GLFWAddress of my code to initialize the Screen, and gladLoadGLLoader worked fine, but it still does not draw the components

**Comment by koorya** [comment]
I think, there was because you link GLFW two times. First in nanogui lib, and second in your base project. I got same troubles, and now i search way to separate nanogui and glfw lidb, for manual manage of linking.
