### ISSUE TITLE
[docs] builds failing due to updated RTD policies

### ISSUE THREAD

**Issue by svenevs** [wjakob/nanogui#308]
Docs builds [are failing](http://readthedocs.org/projects/nanogui/builds/6644062/).

Solution is easy, [uncheck the "install" under Advanced Settings on the admin page](https://github.com/rtfd/readthedocs.org/issues/3296#issuecomment-346463686).

I'm pretty sure that used to be required in order for it to do anything with `docs/requirements.txt`, but if you leave `docs/requirements.txt` as is and uncheck the box the builds will succeed now.  Same thing happened on the exhale testing site.

Once you save that, it should re-build "latest" automatically, but may not.

**Comment by wjakob** [comment]
I disabled the "install" feature and now get the following obscure error message.
<img width="878" alt="screen shot 2018-02-06 at 00 53 35" src="https://user-images.githubusercontent.com/1203629/35834938-3b592d30-0ad8-11e8-9061-942bcdcc0b6c.png">

**Comment by wjakob** [comment]
(There is nothing below the `cat docs/conf.py` line)

**Comment by svenevs** [comment]
Damn.  I'm getting the same problems on the fake site.  I opened a [ticket](https://github.com/rtfd/readthedocs.org/issues/3580) with them, I'll post back when I have more info.

**Comment by svenevs** [comment]
@wjakob it should be fixed now, I added a new release on PyPi so you'll want to make sure to go to the Versions tab on RTD, select `latest`, wipe and then re-build.  I think RTD auto-installs new versions so that may not be necessary, but I feel that's easier than to wait for a potential fail and then have to do that anyway :scream:

**Comment by wjakob** [comment]
It works without problems now -- thank you very much! I'll close this issue then.
