### ISSUE TITLE
Build nanogui as static lib

### ISSUE THREAD

**Issue by clehmann-geo** [wjakob/nanogui#309]
Hello,

I have some trouble building nanogui as a static lib with cmake and Visual Studio C++ 2017 (building as shared lib works perfectly). I tried unticking the NANOGUI_BUILD_SHARED switch in cmake, but that results in linking errors in VS2017.  

I am not sure which else flags I have to change in cmake - could you give me any hints? Thanks in adavance!

**Comment by wjakob** [comment]
You can take a look at Instant Meshes (https://github.com/wjakob/instant-meshes). It uses NanoGUI as a static library.

**Comment by clehmann-geo** [comment]
Okay, thanks!
