### ISSUE TITLE
glew shared library

### ISSUE THREAD

**Issue by mumin16** [wjakob/nanogui#31]
i don't use glew shared library. i removed glew.c from project 
i added glew32.lib to additional dependencies. i used GLEW_BUILD preprocessor definitions. but i still get errors. (LNK2019: unresolved external symbol __glewBindBuffer referenced in function) bla bla..

**Comment by wjakob** [comment]
Sorry, my resources are unfortunately fairly limited. If you change nanogui and it doesn't compile anymore as a result of it, you're on your own ;)
