### ISSUE TITLE
Some pointers on rendering a scene with UI?

### ISSUE THREAD

**Issue by Nanidato** [wjakob/nanogui#312]
Hello, for the past few days I've been playing around with most of nanogui's features and feel pretty comfortable using them at this point, ran into no problems. Now I'd like to take them and actually apply it to a rendering engine I've created, but would like some advice as to how to start (via letting Nanogui handle the window).

I've looked at the docs and darrenmothersele's great example (https://github.com/darrenmothersele/nanogui-test/blob/master/test.cpp) but I have a few questions:

1) In his example, if I'm correct, he is drawing an object in his shaders, and drawing it to a quad, which is then added to the modulation widget?

2) With GLShader it looks like I have to let nanogui handle everything from shader loading to indices. As a result I don't quite understand what's happening here:
    **mShader.init("raymarching_shader",string(vertShader.data(), vertShader.size()),string(fragShader.data(), fragShader.size())** If I'm trying to render a 3D scene with multiple different shaders happening at the same time with some meshes with or without EBO, instancing, etc, how do I get control over that process here?

Thanks in advance!

**Comment by Nanidato** [comment]
Ah, I was being dumb. It was easy to implement nanogui to my project, the widgets just weren't rendering because I included a glclearcolor between their respective render calls. Oops.

**Comment by svenevs** [comment]
Seems like you got it figured out, but knowing the mechanics is useful

https://github.com/wjakob/nanogui/blob/cf576ee1ed53155a9abf356291eb0030dc2f7b3c/src/screen.cpp#L385-L393

During the mainloop, every active screen instance has its `drawAll` method called:

https://github.com/wjakob/nanogui/blob/cf576ee1ed53155a9abf356291eb0030dc2f7b3c/src/common.cpp#L98

The idea here is that all of your OpenGL rendering should go in the `Screen::drawContents` method:

https://github.com/wjakob/nanogui/blob/cf576ee1ed53155a9abf356291eb0030dc2f7b3c/include/nanogui/screen.h#L110-L111

AKA if you want a different clear color, just set `Screen::mBackground` to the desired color.  In your derived screen class, override `drawContents` (don't override `drawAll` unless you really need to).
