### ISSUE TITLE
Question: would it be possible to theme like Blender UI

### ISSUE THREAD

**Issue by sphaero** [wjakob/nanogui#314]
Would it be possible to style or integrate widgets into NanoGUI like the Blender UI? There's a similar project based on NanoVG which mimics the Blender UI: see [blendish-oui](https://bitbucket.org/duangle/oui-blendish/src)

![screenshot](https://bitbucket.org/repo/zAzpBG/images/1457969701-blendish2.png)

Just wondering what it would take. (Hope you don't mind this question through an issue)

Rg,

Arnaud

**Comment by wjakob** [comment]
It's definitely beyond the scope. Why not use Blendish if you like this style?
