### ISSUE TITLE
nsight nvcc / functional(612): error: expression must have a constant value

### ISSUE THREAD

**Issue by ghost** [wjakob/nanogui#315]
My compiler /

thorsten@thorsten-Veriton-M670G-M670:~$ cat bin/nvcc 
#!/bin/sh

XY=""
XY="$XY --expt-relaxed-constexpr "
XY="$XY -std=c++11 "
XY="$XY -ccbin clang-3.8 "
XY="$XY -I/home/thorsten/nanogui/include/ "
XY="$XY -I/home/thorsten/nanogui/ext/eigen/ "
XY="$XY -I/home/thorsten/nanogui/ext/nanovg/src/ "

/usr/bin/nvcc $XY $* -Lnanogui -lstdc++

thorsten@thorsten-Veriton-M670G-M670:~$ 
*******************************************

In NSight /
06:50:09 **** Incremental Build of configuration Release for project FractalStudio ****
make all 
Building file: ../src/FractalStudio.cu
Invoking: NVCC Compiler
/home/thorsten/bin/nvcc -O3 -gencode arch=compute_35,code=sm_35  -odir "src" -M -o "src/FractalStudio.d" "../src/FractalStudio.cu"
/home/thorsten/bin/nvcc -O3 --compile --relocatable-device-code=false -gencode arch=compute_35,code=compute_35 -gencode arch=compute_35,code=sm_35  -x cu -o  "src/FractalStudio.o" "../src/FractalStudio.cu"
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/functional(612): error: expression must have a constant value

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/functional(616): error: expression must have a constant value

2 errors detected in the compilation of "/tmp/tmpxft_0000214f_00000000-7_FractalStudio.cpp1.ii".
src/subdir.mk:18: die Regel für Ziel „src/FractalStudio.o“ scheiterte
make: *** [src/FractalStudio.o] Fehler 2

06:50:14 Build Finished (took 5s.355ms)

**Comment by svenevs** [comment]
Is there any more information here (as in, where is NanoGUI causing this)?  FWIW, this doesn't seem like a valid CUDA setup.  You have `-ccbin clang-3.8`, but then are using the GCC 7.2.0 headers.  What was NanoGUI compiled with on this machine?  The path of least resistance with CUDA tends to be using the default host compiler.

**Comment by gammastorm** [comment]
NanoGui was compiled with GCC 7.2.0
How can I choose the default host compiler ?
actually it is some problem with -std=c++11

**Comment by gammastorm** [comment]
thorsten@thorsten-Veriton-M670G-M670:~$ cat bin/nvcc 
#!/bin/sh

XY=""
XY="$XY --expt-relaxed-constexpr "
XY="$XY -std=c++11 "
XY="$XY -ccbin gcc-5 "

/usr/bin/nvcc $XY $* -Lnanogui -lstdc++

***********************************************************

07:34:06 **** Incremental Build of configuration Release for project FractalStudio ****
make all 
Building file: ../src/FractalStudio.cu
Invoking: NVCC Compiler
/home/thorsten/bin/nvcc -O3 -gencode arch=compute_35,code=sm_35  -odir "src" -M -o "src/FractalStudio.d" "../src/FractalStudio.cu"
/home/thorsten/bin/nvcc -O3 --compile --relocatable-device-code=false -gencode arch=compute_35,code=compute_35 -gencode arch=compute_35,code=sm_35  -x cu -o  "src/FractalStudio.o" "../src/FractalStudio.cu"
/usr/local/include/nanogui/glutil.h(738): error: namespace "std" has no member "isfinite"

1 error detected in the compilation of "/tmp/tmpxft_00002f2d_00000000-7_FractalStudio.cpp1.ii".
src/subdir.mk:18: die Regel für Ziel „src/FractalStudio.o“ scheiterte
make: *** [src/FractalStudio.o] Fehler 2

07:34:11 Build Finished (took 4s.983ms)

**Comment by LuoWDK** [comment]
> thorsten@thorsten-Veriton-M670G-M670:~$ cat bin/nvcc
> #!/bin/sh
> 
> XY=""
> XY="$XY --expt-relaxed-constexpr "
> XY="$XY -std=c++11 "
> XY="$XY -ccbin gcc-5 "
> 
> /usr/bin/nvcc $XY $* -Lnanogui -lstdc++
> 

Approved! I came up with the same question, and I solved it with "gcc-5".

**Comment by svenevs** [comment]
Thanks for sharing what worked for you / confirming.  This does not really have much to do with NanoGUI, so marking as closed.  In general

1. Mixing things built with clang and things built with GCC generally will not work.  It can be done, but not easily and is beyond the scope of this post.
2. If you are reading this post from the future, I encourage you to use the `CUDA` language support with CMake rather than manually calling `nvcc` yourself.  This was introduced in CMake v3.9, and has improved greatly.  It will save you a lot of pain for the typical combos of `gcc / nvcc` or `clang / nvcc`.  Clang as a CUDA compiler is not yet supported in CMake though.
