### ISSUE TITLE
still not solved nvcc nsight ubuntu 17....

### ISSUE THREAD

**Issue by ghost** [wjakob/nanogui#320]
#!/bin/sh

XY=""
#XY="$XY --expt-relaxed-constexpr "
XY="$XY -std=c++11 "
XY="$XY -ccbin clang++-3.8 "

/usr/bin/nvcc $XY $* -lnanogui -lstdc++

******************************************************************
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/math.h:97:12: note: using declaration
using std::log2;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by svenevs** [comment]
This is a compilation error unrelated to nanogui.  More info here https://github.com/wjakob/nanogui/issues/315#issuecomment-493729384
