### ISSUE TITLE
Updating values in a FormHelper

### ISSUE THREAD

**Issue by NathanGarrett** [wjakob/nanogui#323]
Hi, this may be a noob question but I am currently strugling with making the values in the form helper update according to what is happening in my scene. Currently my program allows the user to change the transform (scale, position and rotation) of a 3D model. 
The core issue is that the focus (the object being transformed) is set to the 0th object in the scene which allows me to edit its parameters in the gui, however when I change the focus in the application it is not changed in the gui. 
I've tried using a boolean to tell the application when the gui has been drawn so as not to create a new menu every frame. When I don't use this boolean the gui does update but only because the entire gui is being drawn again and again. 
Am I missing something obvious?
`Window::Window()
{
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);

}

Window::~Window()
{
}

void Window::InitWindow()
{

	// initialise a window and let GLFW know that it should target opengl version 4.3
	glfwInit();
	window = glfwCreateWindow(m_kiWidth, m_kiHeight, "3DModeller", nullptr, nullptr);
	
	
	if (window == nullptr)
	{
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
	}

	// make this new window our current context, THEN try to initialise GLAD function ptrs
	glfwMakeContextCurrent(window);

#pragma region nanoCallBacks
	glfwSetCursorPosCallback(window,[](GLFWwindow *, double x, double y)
	{
		screen->cursorPosCallbackEvent(x, y);
		GLfloat	fxPos = static_cast<GLfloat>(x);
		GLfloat	fyPos = static_cast<GLfloat>(y);

		if (abkeys[GLFW_KEY_LEFT_SHIFT])
		{

			if (bFirstMouse)
			{
				flastX = fxPos;
				flastY = fyPos;
				bFirstMouse = false;
			}
			GLfloat xOffset = fxPos - flastX;
			GLfloat yOffset = flastY - fyPos;

			camera->MouseProc(xOffset, yOffset);
		}
		flastX = fxPos;
		flastY = fyPos;

	}
	);

	glfwSetMouseButtonCallback(window,[](GLFWwindow *, int button, int action, int modifiers) 
	{
		screen->mouseButtonCallbackEvent(button, action, modifiers);
	}
	);

	glfwSetKeyCallback(window,[](GLFWwindow *, int key, int scancode, int action, int mods) 
	{
		screen->keyCallbackEvent(key, scancode, action, mods);
		if (key >= 0 && key <= 1024)
		{
			if (action == GLFW_PRESS)
			{
				abkeys[key] = true;
			}

			else if (action == GLFW_RELEASE)
			{
				abkeys[key] = false;
			}
		}
	}
	);

	glfwSetCharCallback(window,[](GLFWwindow *, unsigned int codepoint) 
	{
		screen->charCallbackEvent(codepoint);
	}
	);

	glfwSetDropCallback(window,[](GLFWwindow *, int count, const char **filenames)
	{
		screen->dropCallbackEvent(count, filenames);
	});

	glfwSetScrollCallback(window,[](GLFWwindow *, double x, double y) 
	{
		screen->scrollCallbackEvent(x, y);
	});

	glfwSetFramebufferSizeCallback(window,[](GLFWwindow *, int width, int height) 
	{
		screen->resizeCallbackEvent(width, height);
	});
#pragma endregion
	
	glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
	//Glad init
	if(!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
	{
		std::cout << "Failed to initialise GLAD" << std::endl;
	}
	//Check if window
	if (nullptr == window)
	{
		std::cout << "Failed to create GLFW window" << std::endl;
		glfwTerminate();
	}
	

	scene = new Scene();
	scene->initScene(*camera);
	
	screen = new nanogui::Screen();
	screen->initialize(window, true);
	
}

void Window::InitUI()
{
	if (!m_bGUIActive)
	{
		nanogui::FormHelper *gui = new nanogui::FormHelper(screen);
		nanogui::ref<nanogui::Window> nanoguiWindow = gui->addWindow(Eigen::Vector2i(10, 10), "Transform");
		gui->addGroup("Scale");
		gui->addVariable("X", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_scale.x)->setSpinnable(true);
		gui->addVariable("Y", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_scale.y);
		gui->addVariable("Z", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_scale.z);
		gui->addGroup("Position");
		gui->addVariable("X", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_position.x);
		gui->addVariable("Y", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_position.y);
		gui->addVariable("Z", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_position.z);
		gui->addGroup("Rotation");
		gui->addVariable("Roll", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_orientation.x);
		gui->addVariable("Pitch", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_orientation.y);
		gui->addVariable("Yaw", scene->m_Objects[scene->GetFocus()]->getComponent<TransformComponent>()->m_orientation.z);
		
		screen->setVisible(true);
		screen->performLayout();
		nanoguiWindow->setPosition(nanogui::Vector2i(10, 10));
		screen->updateFocus(nanoguiWindow);
		m_bGUIActive = true;
	}	
	
}

void Window::Update()
{
	while (!glfwWindowShouldClose(window))
	{
		GLfloat currentFrame = static_cast<GLfloat>(glfwGetTime());
		fDeltaTime = currentFrame - lastframe;
		lastframe = currentFrame;
		
		glClearColor(0.5f, 0.5f, 0.5f, 0.f);
		
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
				
		glfwWaitEvents();

		DoMovement();
				glDisable(GL_DEPTH_TEST);

		screen->drawContents();
		screen->drawWidgets();

		glEnable(GL_DEPTH_TEST);
		Render();

		// swap buffers i.e. draw to screen
		glfwSwapBuffers(window);
		//onCLick();
		
	}
}

void Window::Render()
{
	if (scene->m_Objects.size() < 1) { scene->GenModel("cube.obj"); }
	if (abkeys[GLFW_KEY_W])
	{
		scene->m_Objects[0]->getComponent<TransformComponent>()->translate(glm::vec3(0, 1, 0));
	}
	if (abkeys[GLFW_KEY_LEFT_CONTROL] && abkeys[GLFW_KEY_TAB])
	{
		scene->CycleFoci();
		std::cout << scene->GetFocus() << std::endl;
	}
	if (abkeys[GLFW_KEY_LEFT_CONTROL] && abkeys[GLFW_KEY_LEFT_SHIFT])
	{
		scene->CycleModes();
	}
	if (abkeys[GLFW_KEY_RIGHT_CONTROL] && abkeys[GLFW_KEY_C])
	{
		scene->GenModel("cube.obj");
	}
	InitUI();
	scene->render(*camera);
}`

I hope having such a large snippet doesn't break the rules haha. Any advice you can give would be greatly appreciated thank you.

**Comment by svenevs** [comment]
1. Please fix the markdown.  You started and ended with a single back-tick, for code-blocks you need to use three:

        ```cpp
        // paste code
        ```
    noting that the three back-ticks are on their own lines.
2. That's quite a lot of code.  I don't think many people will have the bandwidth to figure it all out.
3. I'm not actually sure you can do this.  Here is the real issue:

    ```cpp
    gui->addVariable("Y", scene->m_Objects[scene->GetFocus()]->getComponent()->m_scale.y);
    ```

    Suppose you had two meshes, `A` and `B` and `scene->m_Objects = {A, B}`, and `scene->GetFocus()` is `0`.  This means that variable `"Y"` is constructed and bound to `A->getComponent()->m_scale.y`.  At some later point `scene->GetFocus()` is returning `1` to indicate `B->getComponent()->m_scale.y` should be changed, **but this will never happen** because when the variable was created you bound it directly to `A->getComponent()->m_scale.y`.
4. I'm not sure there is a way around that in the FormHelper, but you can look in the source code to see.  It may just be better to set this up manually.  You can create a `FloatBox<float>` for example, and set its callback (see `example1.cpp`).  Then in the callback, you can capture `[scene]` and update the current object in focus.  Or at least I think that's what you're trying to do?
