### ISSUE TITLE
Video player widget (want to contribute, help needed).

### ISSUE THREAD

**Issue by rvega** [wjakob/nanogui#328]
I'm currently working on a audio application for Linux and Windows and using nanogui for the interface.
I need to integrate some video content in the app, for which I'll use libvlc. 

I have successfully opened two glfw windows with nanogui (two instances of Screen) and using one of them for some nanogui widgets and the other one for the video player, similar to [this libvlc example](https://wiki.videolan.org/LibVLC_Tutorial/#Linux).

Now, I need to integrate the video content within the same window (nanogui Screen) as the other nanogui widgets so I want to implement a video player Widget. I saw [this other libvlc example](https://wiki.videolan.org/LibVLC_SampleCode_SDL/) where they take the pixel information from libvlc and render it into a SDL layer.  

I'm not familiar with GL programming at all. My question is ¿What would be the general approach in nanogui to create such Widget? I'm guessing I'll have to create some sort of GL canvas that gives me a "render" or an "update" callback and in that callback I can render the pixel data that I get from libvlc. 

Any advice will be appreciated.

**Comment by crazycarl** [comment]
I can think of two directions for you to start from.
If you want to go with crude OpenGL, Example 4 shows you how to use raw OpenGL calls with shaders inside a widget. A good place to learn reasonably modern OpenGL is [https://learnopengl.com/](url).

Another approach would be to look into how ImageView is implemented. This will likely still require some raw OpenGL to load the frames into video memory.

**Comment by rvega** [comment]
Thanks @crazycarl. I've made some progress by creating a shader that draws a square, applying a texture to the square and setting the pixel data for the texture with glTexImage2D(). The video, however, is looking very weird, as if there was no red channel and with a lot of noise. 

Also, when I move the mouse within the nanogui screen, there are a lot of frames that are not drawn. 

See a demonstration here: https://youtu.be/Udm2j4hzAj8
And the code: https://gist.github.com/rvega/a25b1f594701f7df1e4c8e89a6e5b318

Any help fixing this would be appreciated :)

**Comment by crazycarl** [comment]
Its looking like you based this off of the ImageView widget, which was a good idea.

It looks like your shader code and texture loading are correct, but it looks like you may have skipped a step when binding the texture to the shader.

Notice that the ImageView sets the uniform for the 2d scalar to 0 here: [https://github.com/wjakob/nanogui/blob/be13c9b8300851fe9956bac5877468b5b58932dc/src/imageview.cpp#L309](url)

That tells it to use texture unit 0. Then you bind the texture to texture unit 0 here: [https://github.com/wjakob/nanogui/blob/be13c9b8300851fe9956bac5877468b5b58932dc/src/imageview.cpp#L307](url)

Some video drivers will make assumptions and default the active texture unit to 0, but not all drivers are guaranteed to do that at all times. This may be why the behavior is somewhat hard to define here.

I haven't tried playing around with this since I don't have the VLC library installed, so I'm not %100 sure this is the problem. Hopefully my hunch on this is right.

This more proper tutorial on textures may help you. The section on Texture Units is probably what you are most interested in.
[https://learnopengl.com/Getting-started/Textures](url)

One last note, I notice that you allocate memory for pixelBuffer, but I don't see where that's cleaned up during destruction. I may have just missed it.

**Comment by svenevs** [comment]
I've run into similar issues with `GLCanvas` in the past, and as @crazycarl explains it was related to texture units.  I never got to the bottom of the issue, but the underlying NanoVG library modifies `GL_TEXTURE0` state (this is a promise).  `nanogui::ImageView` has no issue using this directly, but I ran into a lot of problems with it on a `GLCanvas`, the solution was to just use a different texture unit altogether (e.g., `GL_TEXTURE1`).

I threw together a really sloppy example here: https://gist.github.com/svenevs/486115e7e9fefb224dfe55304e563250

If you run it with cmd input `0` and it glitches, but `1` and it does not, this may be specific to your video driver.  Anyway, see the `drawGL` method for how you use texture units, you should be able to mostly just drop that into your existing code?  I gave a suggestion on how to restructure your canvas widget (the `newFrame` method in conjunction with `drawGL`), I think you may run into trouble down the line depending on how threading and VLC works.  The example code is how I did things for a live webcam.

I hope it is more helpful than confusing...

**Comment by rvega** [comment]
Thank you very much @svenevs  and @crazycarl. It is now working fine :) 
I started from svenevs' example and replaced the image loader class there with actual libVLC code and it's all fine now.
I'll come back after I clean up my code and post my progress.

**Comment by rvega** [comment]
Here is the code so far: https://gist.github.com/rvega/18d84addc474a4175d3b72c091d7aaae

I'd like to actually contribute something to this public repo. Here's some stuff to discuss:

1. Is there interest in such a video canvas widget for nanogui, or you guys think this is very app-specific? This could simply be a repo that I can maintain as an example of use of nanogui or it could be further developed into a widget to be included in the library.

2. Maybe adding libvlc as a dependency is too much? I was thinking the dependency could be optional and turned off by default somehow in the cmake config. Should the libvlc code be included in the ext folder or requiring libvlc to be installed in the developer's machine is ok?

3. A possible api. Some work would be required to support sensible (re)sizing of the widget.

    ```cpp
        class NANOGUI_EXPORT VideoCanvas: public GLCanvas {
        public:
            /**
             * \brief Creates a video canvas attached to the specified parent.
             *
             * \param parent
             *     The \ref nanogui::Widget this VideoCanvas will be attached to.
             *
             * \param filename 
             *     The path to the video file that will be played.
             */
            VideoCanvas(Widget *parent, const std::string &filename);
            
            /// Start playback
            void play();

            /// Stop playback
            void stop();

            /// Set/unset pause 
            void pause(bool pauseState);

            /// Get video's total duration, in seconds
            int duration();

            /// Get current playback position 
            int position();

            /// Set current playback position 
            void SetPosition(int position);

        protected:
            /// The gl shader used to render the video content
            nanogui::GLShader mTexShader;

            /// The id of the gl texture used to render the video content
            GLuint mTex;

            /// A mutex used internally to keep bad stuff from happening
            std::mutex mDataMutex;

            /// The pixel data loaded from the video at each frame
            char *mData = nullptr;

            /// Wether new data is ready to be drawn or not
            bool needUpdate;

            /// An instance of Libvlc used to decode video file
            libvlc_instance_t *vlc;

            /// The media player object from lib vlc
            libvlc_media_player_t *mediaPlayer;

        public:
            EIGEN_MAKE_ALIGNED_OPERATOR_NEW
        }
        NAMESPACE_END(nanogui)

    ```

**Comment by rvega** [comment]
Regarding #2, compiling libvlc is not so easy. Specially on windows.

https://wiki.videolan.org/Compile_VLC/
https://wiki.videolan.org/Win32Compile/

**Comment by crazycarl** [comment]
Some developers may want to use a different decoder library as well, or have different intents for the video view (such as @svenevs webcam). Maybe you should make this more of a generic widget that calls a function to grab its next frame? Something a little more generic that you could easily integrate most libraries into. It just needs you to feed it an array of pixel data.

I wouldn't recommend putting the libVLC into the project like this, but maybe as an optional sub-repository. Of course, I don't manage this repository. This isn't my call to make.

**Comment by wjakob** [comment]
Hi @rvega,

I think it's useful to have this conversation here in case others want to implement a widget like this in the future. However, it's much too specific of a widget to include in NanoGUI.

Since you seem to have the basic version running, I'll go ahead and close this ticket.

Best,
Wenzel
