### ISSUE TITLE
Nanogui segfaults on shutdown(), caused by a bug in glfw that was fixed two years ago

### ISSUE THREAD

**Issue by avasilkov** [wjakob/nanogui#342]
BUG

When I close an example, I get segfault during nanogui::shutdown() in glfw terminate.
Happens on every launch of any example1-3 on my machine, 

http://discourse.glfw.org/t/weird-segfault-in-xclosedisplay-called-from-glfwterminate/703
Confirmed the issue by doing this
>Thought of a quicker way than a full bisect: instead of commenting out the call to _glfwTerminateEGL, comment out the call to _glfw_dlclose in that function in egl_context.c. That shouldn’t segfault either.
Fixed by this commit: https://github.com/glfw/glfw/commit/d5e00e6

I've tried merging up to this commit into the current submodule here - there were no conflicts and it started finishing without a segfault.

**Comment by svenevs** [comment]
Cross-ref #347 .  This should hopefully be resolved soon.

**Comment by merlinND** [comment]
@avasilkov Would you be able to check if this is resolved with the latest `master`?

**Comment by avasilkov** [comment]
@merlinND just pulled the repo into a new folder and compiled, there are no segfault messages on exit anymore.
