### ISSUE TITLE
Naked pointers in examples

### ISSUE THREAD

**Issue by pauljurczak** [wjakob/nanogui#345]
The code examples follow this pattern: 
```
Screen *screen = new Screen(Vector2i(500, 700), "NanoGUI test");
```
without corresponding `delete`, which leaks resources, unless there is some magic behind the screen. Why not:
```
auto screen = Screen{Vector2i(500, 700), "NanoGUI test"};
```
as in [darrenmothersele/nanogui-test](https://github.com/darrenmothersele/nanogui-test/blob/master/test.cpp).

**Comment by svenevs** [comment]
There is magic :) see #230 for now information.

**Comment by pauljurczak** [comment]
Thank you! That's exactly what I was looking for.
