### ISSUE TITLE
Crashing when changing mTextColor

### ISSUE THREAD

**Issue by GitFury** [wjakob/nanogui#349]
`ColorWheel* wheel = settings_tab->add<ColorWheel>();
wheel->setCallback([&](const Color &color) {
	window->theme()->mTextColor = color;
});`

I'm getting an unexpected crash here whenever I click anywhere on the colorwheel, I'm probably doing something wrong. Please correct my mistake.

**Comment by svenevs** [comment]
Unclear from the posted code but if I had to bet I'd say it's a problem with capturing `[&]`. Does it work if you capture `[window]` instead?

**Comment by GitFury** [comment]
It works, thank you so much! On the other hand, I do have a question.
I'm unfamiliar with event based GUI's I'm more familiar with something such as ImGui (immediate mode GUI). How would I be able to regularly update the text colors based on a time interval this way? (excuse my ignorance).

**Comment by GitFury** [comment]
Nevermind, you may now close this.
