### ISSUE TITLE
update nanovg dependency to latest version

### ISSUE THREAD

**Issue by wkjarosz** [wjakob/nanogui#351]
Hi Wenzel,

Nanogui currently uses a version of nanovg from over a year ago. Several issues have been fixed in nanovg in that time (notably for my project, additive alpha blending now works).

Is there any chance nanogui's nanvg submodule could be updated to the latest version?

Thanks.

**Comment by wjakob** [comment]
I Wojciech -- sorry, I never saw this message. (I get really overwhelmed with github tickets from various open source projects at times). FWIW, @svenevs just upgraded the underlying NanoVG.
