### ISSUE TITLE
how to build nanogui from source [WINDOWS]

### ISSUE THREAD

**Issue by NavaneethRao** [wjakob/nanogui#352]
hey,
i tried build from source but i get this error The NanoGUI dependency repositories (GLFW, etc.) are missing! You probably
  did not clone the project with --recursive.  It is possible to recover by
  calling "git submodule update --init --recursive"

What should i do?

**Comment by svenevs** [comment]
`

**Comment by svenevs** [comment]
Sorry for the accidental close with no response!

`git submodule update --init --recursive`

Is the command you need to execute. Sounds like you pointed visual studio to where `CMakeLists.txt` is. You need to open up a command prompt or powershell, `cd` to wherever you cloned NanoGUI, and execute the above command :smile:

**Comment by NavaneethRao** [comment]
@svenevs thanks, i have managed to build it and get the lib and dll. now i have another issue my program is breaking at #if defined(NANOGUI_GLAD)
    if (!gladInitialized) {
        gladInitialized = true;
        if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
            throw std::runtime_error("Could not initialize GLAD!");
        glGetError(); // pull and ignore unhandled errors like GL_INVALID_ENUM
    }
#endif

beacuse i dont have glad.lib do u know where i can get them?

if you have discord i would love to contact you _Rize#2399

**Comment by NavaneethRao** [comment]
basically i have included glad but i can find the .lib's to include it.

**Comment by NavaneethRao** [comment]
EDIT: ok i can include glad now (i just dragged glad.c to vs project).

but i crash at this:
![image](https://user-images.githubusercontent.com/32010211/44096361-b57bcda6-9ff8-11e8-9836-5fc341b5e8ca.png)

i dont know why

**Comment by svenevs** [comment]
Ok. It's not really clear what you are doing (are you just trying to build NanoGUI, or use it for a parent project)?

Anyway, seems like you should check out the [compilation docs](http://nanogui.readthedocs.io/en/latest/compilation.html#), it covers both use cases.  Particularly, in your parent project's `CMakeLists.txt` you need the [Required Variables Exposed](http://nanogui.readthedocs.io/en/latest/compilation.html#required-variables-exposed) section.  On windows, `${NANOGUI_EXTRA_LIBS}` contains GLAD.

**Comment by NavaneethRao** [comment]
i have finsihed building it nanogui. 
![image](https://user-images.githubusercontent.com/32010211/44097711-0b43f7ec-9ffc-11e8-97ac-e20fb772745e.png)
i have included glad and put glad.c in the source files. I AM TRYING TO MAKE NANOGUI WORK WITH MY GAME.

**Comment by NavaneethRao** [comment]
ok thanks sorry misread the text. ill check if it works now

**Comment by NavaneethRao** [comment]
ok so i have done this
![image](https://user-images.githubusercontent.com/32010211/44098145-0abb8f50-9ffd-11e8-8a56-210ddf048784.png)

but i am not sure what these mean
can u send me a screenshot (I AM NOOB)
 On top of adding the path to nanogui/include, you may need extras
include_directories(${NANOGUI_EXTRA_INCS})

# Compile a target using NanoGUI
add_executable(myTarget myTarget.cpp)

# Lastly, additional libraries may have been built for you.  In addition to linking
# against NanoGUI, we need to link against those as well.
target_link_libraries(myTarget nanogui ${NANOGUI_EXTRA_LIBS})

**Comment by svenevs** [comment]
> I AM TRYING TO MAKE NANOGUI WORK WITH MY GAME

:laughing:

You'll get there.  Remove `glad.c` from your project, you shouldn't need it and more importantly it can cause conflicts if you have GLAD compiled in there twice.  Let NanoGUI handle those details.

Please post your game's **full** `CMakeLists.txt`, otherwise I can't really help you ;)  Note that you can share code in code blocks

    ```cmake
    # some cmake code, start with 3 back-ticks
    # the 'cmake' after the starting backticks indicate the "lexer" (language)
    target_link_libraries(my-game nanogui ${NANOGUI_EXTRA_LIBS}
    # end it with three backticks too
    ```

will show up like this

```cmake
# some cmake code, start with 3 back-ticks
# the 'cmake' after the starting backticks indicate the "lexer" (language)
target_link_libraries(my-game nanogui ${NANOGUI_EXTRA_LIBS}
# end it with three backticks too
```

so just copy-paste it.  Pictures aren't as useful in this context :)  I've also edited your post above since as you can see the comments get treated funny, because `#` indicates headers (in the html sense).

**Comment by NavaneethRao** [comment]
1. **how do i know if glad is there in my project?**

2. In [Required vars](http://nanogui.readthedocs.io/en/latest/compilation.html#required-variables-exposed) i saw 
Various preprocessor definitions have been generated by NanoGUI
add_definitions(${NANOGUI_EXTRA_DEFS})

On top of adding the path to nanogui/include, you may need extras
include_directories(${NANOGUI_EXTRA_INCS})

Compile a target using NanoGUI
add_executable(myTarget myTarget.cpp)

Lastly, additional libraries may have been built for you.  In addition to linking
against NanoGUI, we need to link against those as well.
target_link_libraries(myTarget nanogui ${NANOGUI_EXTRA_LIBS})

**I pasted these in my preprocessor def in vs:** 

WIN32
_WINDOWS
_CRT_SECURE_NO_WARNINGS
NANOGUI_SHARED
NVG_SHARED
GLAD_GLAPI_EXPORT
NANOGUI_GLAD
CMAKE_INTDIR="Debug"

and removed "**glad.c**"

but i still break at 
```c
#if defined(NANOGUI_GLAD)
    if (!gladInitialized) {
        gladInitialized = true;
        if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
            throw std::runtime_error("Could not initialize GLAD!");
        glGetError(); // pull and ignore unhandled errors like GL_INVALID_ENUM
    }
#endif
```

**Comment by svenevs** [comment]
@NavaneethRao you need to slow down a little.  You cannot just "copy-paste" things to VS and expect it to work.  You need to create a proper parent project `CMakeLists.txt`, and generate a visual studio solution project using CMake.  That's the `-G` flag shown at the beginning of the docs, as an example for building NanoGUI itself.  You do the same thing for your parent project.

Since NanoGUI only supports a CMake build system, I can't help you with what you are trying to do -- I don't know Visual Studio well enough, and don't know if what you are doing is even possible.

I will respond with further assistance when you share your game's `CMakeLists.txt`.  I am going offline now though, so will check in later tonight.

**Comment by NavaneethRao** [comment]
from what i understand we are making a dupilcate project of the source build right?

**Comment by NavaneethRao** [comment]
Ok sorry for being in a rush. I'll try to make a parent project with -G option. Could you advise me on any good cmake tutorials.

**Comment by NavaneethRao** [comment]
![image](https://user-images.githubusercontent.com/32010211/44132437-5c4a52b4-a077-11e8-8c52-a4e8a00adc12.png)

hey i am trying to make a parent project with cmake and slowly understanding cmake build system but i dont see ext/nanogui folder. Here's my dir setup 

![image](https://user-images.githubusercontent.com/32010211/44132470-86b2a74a-a077-11e8-8706-6c0b1063a6db.png)

**Comment by NavaneethRao** [comment]
i am closing this issue and reopening a new one

**Comment by NavaneethRao** [comment]
http://docs.decodestudios.in/

**Comment by NavaneethRao** [comment]
@svenevs sorry for being this way, I learnt a lot of c++ and CMake's build system now. Although i have 1 major question can we link the .dll and lib statically like GLFW?

**Comment by svenevs** [comment]
At the time of writing this, you would want to configure with the cmake argument `NANOGUI_SHARED=OFF` to build a static nanogui library.  This will have GLFW bundled inside of it.  On windows, you typically want to build shared libraries always, because dealing with DLLs is annoying ;)
