### ISSUE TITLE
Error: Eigen/Core: No such file or directory

### ISSUE THREAD

**Issue by LinArcX** [wjakob/nanogui#356]
Hi. i am developing an application using this library in qt. when i want to test __example2__ the compiler say:
```
/usr/include/nanogui/common.h:28: error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
          ^~~~~~~~~~~~
```
I look into new eigen source code and it will be change to:
`#include <eigen3/Eigen/Core>`

**Comment by patrikhuber** [comment]
You need to fix your include path, `Eigen/Core` is the correct way to include Eigen headers. See for example [here](http://eigen.tuxfamily.org/dox/GettingStarted.html).
