### ISSUE TITLE
Canvas element with panning feature which renders elements only in the Viewport

### ISSUE THREAD

**Issue by BassMunkee** [wjakob/nanogui#357]
I came across NanoGUI when exploring the options for a lightweight GUI toolkit and it seemed to fit my use case very well. I'm new to OpenGL and C++ so pardon my 'newb' issue/query.

I was looking at instantiating about 5-10k window objects and placing them in a 'screen' which supports panning (scroll in x and y direction). I was initially hoping to add scroll feature to a subclassed screen object but the performance really deteriorates when I have anything more than 200 objects at once (This is on a macOS on a Core i7 2017 MacBook Pro 15) and the interface lags when I do any operation. I looked into it a bit more and I feel some sort of lazy loading and rasterization of rendered elements may help. 

I'm looking for pointers to go in the right direction to implement such a feature and contribute it back to NanoGUI. I wasn't sure where I can ask such questions as feature requests are not really encouraged (without any implementation). Thanks.

**Comment by wjakob** [comment]
Sorry, we can't provide any support for this -- you'll have to experiment on your own.

**Comment by BassMunkee** [comment]
No worries, thanks for considering. I'll look into this more when I can. Thanks for the awesome framework and look forward to updates on mitsuba.
