### ISSUE TITLE
glUniformli:identifier not found

### ISSUE THREAD

**Issue by vamsigali** [wjakob/nanogui#365]
I am trying to create a new dialog , i have written the code for dialog and while building i am getting following two errors

>Error	C4996	'_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	LearningNanoGui	d:\nanogui\nanogui\include\nanogui\layout.h	423	

> Error	C3861	'glUniform1i': identifier not found	LearningNanoGui	d:\nanogui\nanogui\include\nanogui\glutil.h	249	

i have included the libraries but the issue is not resolved

**Comment by vamsigali** [comment]
I have solved the issue

**Comment by elegracer** [comment]
@vamsigali I've run into this issue too, on Windows with MSVC, how did you solve this?

**Comment by GRAPHENE9932** [comment]
@vamsigali Thank you...

**Comment by Genjo00** [comment]
'glUniform1i' is defined in the glad dependency of nanogui, the error means that this is not added correctly to your project.
First of all, check that something like this is present in your CMakeList.txt *after* the subdirectory of nanogui is added:
```
target_link_libraries(MyProject PRIVATE nanogui ${NANOGUI_EXTRA_LIBS})
target_include_directories(MyProject PRIVATE ${NANOGUI_EXTRA_INCS})
target_compile_definitions(MyProject PRIVATE ${NANOGUI_EXTRA_DEFS})
```
If this doesn't solve the issue, the variable NANOGUI_USE_GLAD is probably set wrong in nanogui's CMakeList.txt
