### ISSUE TITLE
Can't draw without using shaders?

### ISSUE THREAD

**Issue by amurices** [wjakob/nanogui#373]
Trying to use nanogui for my Monte Carlo simulation of a simple 2D surface, whose rendering I'd already written entirely and which does not require shaders. Trying to make `example1` work by drawing, instead of its `mShader`, a simple line that should cut the screen in half, but no matter how I tweak the calls or what I do, it never happens. The nanogui screen simply doesn't draw anything (if I use the original code, however, a rotating square appears). Here's the code: 
```
virtual void drawContents() {
        // ORIGINAL CODE: vvvvvvvvvvvvvvvvvvvvvvv
        // using namespace nanogui;

        /* Draw the window contents using OpenGL */
        // mShader.bind();

        // Matrix4f mvp;
        // mvp.setIdentity();
        // mvp.topLeftCorner<3,3>() = Matrix3f(Eigen::AngleAxisf((float) glfwGetTime(),  Vector3f::UnitZ())) * 0.25f;

        // mvp.row(0) *= (float) mSize.y() / (float) mSize.x();

        // mShader.setUniform("modelViewProj", mvp);

        // /* Draw 2 triangles starting at index 0 */
        // mShader.drawIndexed(GL_TRIANGLES, 0, 2);

        // MY CODE (doesn't draw): vvvvvvvvvvvvvvvvvvvvvvv
        float ratio;
        int width, height;
        ratio = width / (float)height;
        glViewport(0, 0, width, height);
        glClear(GL_COLOR_BUFFER_BIT);
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glOrtho(-ratio, ratio, -1.f, 1.f, 1.f, -1.f);
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        glRotatef((float)glfwGetTime() * 50.f, 0.f, 0.f, 1.f);
        glBegin(GL_LINES);
        glColor3f(1.f, 0.f, 0.f);
        glVertex3f(-1.0f, 0.0f, 0.f);
        glColor3f(0.f, 1.f, 0.f);
        glVertex3f(1.0f, 0.0f, 0.f);
        glEnd();
    }
```

Something else I've done trying to achieve this is make very similar changes to `example3.cpp`, by extending the `Screen` class with a very brief override of the `drawContents()` method, like so:
```
class MyMan : public nanogui::Screen{
    public:
    virtual void drawContents() {
       float ratio;
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glOrtho(0.0, 0, 0, 0.0, -1.0, 1.0);
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
         
        glBegin(GL_LINES);
        glColor3f(0.5f, 0.5f, .5f);
        glVertex2f(0, 1);
        glColor3f(0.5f, 0.5f, .5f);
        glVertex2f(0, -1);
        glColor3f(0.5f, 0.5f, .5f);
        glVertex2f(1, 0);
        glColor3f(0.5f, 0.5f, .5f);
        glVertex2f(-1, 0);
        glEnd();
    }
};

MyMan *screen = nullptr;
```
Which also does not work.

Here are my changes:
https://github.com/wjakob/nanogui/compare/master...amurices:master

**Comment by svenevs** [comment]
Hi @amurices unfortunately this is not supported. What you are trying to do is "fixed function pipeline", which is OpenGL 2.x and deprecated.  NanoGUI only supports 3.3 and later.  There's a bit more information of how you might go about putting back OpenGL 2 support in #212 but it's not exactly easy.

You can still do 2D with shaders, but you'll need to create a shader and directly upload vertices / indices etc.  For example, you would be doing `mShader.drawIndexed(GL_LINES, 0, /* however many lines you added */)`.  That can be a little confusing to learn, but I think it would be a better use of your time to learn shaders than to try and backport nanogui to use OpenGL 2.x.

The only other thing that you may find useful is there are some convenience functions in `nanogui/glutil.h` such as `nanogui::frustum` or `nanogui::ortho` that can help you build the desired matrices for the mvp matrix you want to upload.  Hope that helps some.

**Comment by amurices** [comment]
Hi @svenevs 

That's helpful for sure. Thanks so much for your time and attention. I'll have a look into some basic shader programming.
