### ISSUE TITLE
drawWidgets overlay other render object 

### ISSUE THREAD

**Issue by egino135** [wjakob/nanogui#375]
when I run screen->drawWidgets(),my screen->drawContents() or other object cant render

	while (!glfwWindowShouldClose(window)) 
	{
		GLfloat currentFrame = (float)glfwGetTime();
		deltaTime = currentFrame - lastFrame;
		lastFrame = currentFrame;

		// Check if any events have been activated (key pressed, mouse moved etc.) and call corresponding response functions
		glfwPollEvents();
		cameraMove();

		glm::mat4 view_matrix = camera.GetViewMatrix();
		glBindBuffer(GL_UNIFORM_BUFFER, uboMatrices);
		glBufferSubData(GL_UNIFORM_BUFFER, sizeof(glm::mat4), sizeof(glm::mat4), glm::value_ptr(view_matrix));
		glBindBuffer(GL_UNIFORM_BUFFER, 0);

		//render
		// Define the viewport dimensions
		glViewport(0, 0, WIDTH, HEIGHT);

		glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

		screen->drawContents();
		screen->drawWidgets();

		// swap buffers i.e. draw to screen
		glfwSwapBuffers(window);
		//onCLick();
	}
 
screen is a instance of MyScreen

```cpp
class MyScreen : public nanogui::Screen
{
public:
	MyScreen(Shader& shader, VAO& vao)
		: nanogui::Screen(), shader(shader), vao(vao)
	{
		this->model_matrix = glm::mat4();
	}
	virtual void drawContents() override
	{
		this->shader.Use();
		glUniformMatrix4fv(glGetUniformLocation(this->shader.Program, "model_matrix"), 1, GL_FALSE, glm::value_ptr(this->model_matrix));

		glBindVertexArray(this->vao.number);
		glDrawArrays(GL_TRIANGLES, 0, this->vao.count);
		glBindVertexArray(0);

	}
	
private:
	glm::mat4 model_matrix;
	Shader& shader;
	VAO& vao;
};
````

I want show GUI and 3D object in same time
thanks

**Comment by svenevs** [comment]
Hi @egino135,

When managing GLFW yourself you need to call `Screen::initialize`

https://github.com/wjakob/nanogui/blob/4b6133d2c82769f1b03762f3a7390d6884756a62/src/example3.cpp#L92-L93

It doesn't appear that you are calling that anywhere, but I'm not sure if the above code is the full example.  Please reopen if that is not the problem here, but it seems likely because without calling `initialize` with the `window`, the widgets don't know where to draw things.

**Comment by egino135** [comment]
thanks @svenevs ,
I already find my bug,
because of UBO(uniform binding), I have no re-binding after render widgets of nanoGUI
(I think that nanogui use UBO, too)
