### ISSUE TITLE
Is file picker supported in nanogui?

### ISSUE THREAD

**Issue by jialiuBellus3d** [wjakob/nanogui#390]
Just wondering cuz I haven't found anything similar in the header files.
Thanks.

**Comment by svenevs** [comment]
I think you are asking about `nanogui::file_chooser`, which are defined in `nanogui/common.h` (and implemented in `src/common.cpp`.  The definitions are here

https://github.com/wjakob/nanogui/blob/4b6133d2c82769f1b03762f3a7390d6884756a62/include/nanogui/common.h#L463-L495

Sample usage is here:

https://github.com/wjakob/nanogui/blob/4b6133d2c82769f1b03762f3a7390d6884756a62/src/example1.cpp#L285-L298
