### ISSUE TITLE
Invalid Eigen commit

### ISSUE THREAD

**Issue by SunMaungOo** [wjakob/nanogui#391]
I try to clone the repo and it said it doesn't found the commit `cf794d3b741a6278df169e58461f8529f43bce5d ` of the eigen sub module.

`error: no such remote ref cf794d3b741a6278df169e58461f8529f43bce5d
Fetched in submodule path 'ext/eigen', but it did not contain cf794d3b741a6278df169e58461f8529f43bce5d. Direct fetching of that commit failed.
`

**Comment by svenevs** [comment]
I'm not able to reproduce this.  We switched it to the official mirror using a shallow submodule, I suspect that you have a rather old version of `git`.  What is `git --version`?  What's your OS?  [This is the commit in question](https://github.com/eigenteam/eigen-git-mirror/tree/cf794d3b741a6278df169e58461f8529f43bce5d), which is the tag of v3.3.7

**Comment by SunMaungOo** [comment]
The problem occurs because I am using the old version of git (git version 2.10.1.windows.1). When I update 
to the latest version of git , it works.
