### ISSUE TITLE
Is it possible for a widget to have it's own theme instead of using window's theme?

### ISSUE THREAD

**Issue by jialiuBellus3d** [wjakob/nanogui#395]
Right now if I have widgetA widgetB in a window
widgetA->theme() only has some window color option like mWindowFillFocused 
So changing this would cause the whole window theme change which affects widgetB as well

Is there a way to set single widget background color, corner radius and so on?

**Comment by svenevs** [comment]
Hi @jialiuBellus3d, a rough sketch of how to accomplish this if you really wanted to:

```cpp
#include <nanogui/nanogui.h>

int main() {
    nanogui::init();

    {
        auto *screen = new nanogui::Screen({400, 400}, "Password Textbox", false);

        auto *window = new nanogui::Window(screen, "Some Window");
        window->setLayout(new nanogui::GroupLayout());
        window->setSize({300, 300});
        window->setFixedSize({300, 300});
        window->center();

        new nanogui::Label(window, "The Password");
        new nanogui::CheckBox(window, "Default CheckBox");// just for reference

        auto *cb = new nanogui::CheckBox(window, "A Custom CheckBox");

        // 1. create a new theme instance
        auto *custom_theme = new nanogui::Theme(screen->nvgContext());
        // 2. customize it however you want
        // vvv does not actually do what you are describing
        custom_theme->mWindowFillFocused = {1.0f, 0.0f, 0.0f, 1.0f};
        // vvv this would do it globally for this window
        // screen->theme()->mWindowFillFocused = {1.0f, 0.0f, 0.0f, 1.0f};
        custom_theme->mCheckBoxIcon = ENTYPO_ICON_CROSS;
        // 3. set theme of the widget you want to change
        cb->setTheme(custom_theme);

        screen->performLayout();
        screen->setVisible(true);
        nanogui::mainloop();
    }

    nanogui::shutdown();
    return 0;
}
```

**However**, this kind of goes against the intended purpose of the theme class / you need to be a little cautious:

1. Every time you create a theme, the font memory is loaded.  So if you create 20 themes, `"sans"` and `"sans-bold"` are loaded 20 times.  Font memory cannot be deleted at this time, either.
2. Generally speaking, all of the window colors are only relevant for the drawing of the window class.  If you want a Widget to have a specific color background, you are probably better off creating a custom class to achieve this.
    - Widgets are drawn back to front, so the window gets drawn first, then the checkboxes get drawn.

For example, the `nanogui::Button` class allows for a custom background color and is a good reference for you to use in your custom widget classes.  Your widget just needs to override `Widget::draw`, see method here and look at the stuff revolving around `mBackgroundColor` for how to go about coloring specific widgets to your hearts desire

https://github.com/wjakob/nanogui/blob/aeebc45344299bf318fbdede3196b26e60d33fcd/src/button.cpp#L106

Hope that is what you are looking for.  If not please feel free to re-open and be more specific about what you want changed / how :slightly_smiling_face:
