### ISSUE TITLE
eigen 3.2.4 has memory issue on MSVC 2015

### ISSUE THREAD

**Issue by TerranRush** [wjakob/nanogui#40]
I've encountered a crash when I call slice() function of libigl in debug mode.
The problem seems due to the Eigen 3.2.4 ("libigl\external\nanogui\ext\eigen") under MSVC 2015.
The latest Eigen does not have such problem. Maybe you guys could update Eigen too.

**Comment by wjakob** [comment]
This is not a nanogui issue. I suggest you file it at Eigen or libigl.
