### ISSUE TITLE
(linux)nanogui hanging on poll.c:29

### ISSUE THREAD

**Issue by MylesLeadbeater** [wjakob/nanogui#414]
I'm trying to use NanoGUI in a project, but the app/s are hanging on poll.c:29. This is happening seemingly randomly, as it works perfectly fine sometimes.

The NanoGUI Examples are having the same issue, so I'm lead to believe there is either an issue with NanoGUI, linking, or something installed badly on my machine.

To reproduce on my machine:

git clone --recurse-submodules git@github.com:wjakob/nanogui.git nanogui.git
cd nanogui.git
mkdir build
cd build
cmake ..
make
./example_icons

I have a call stack, This one is from running the example 'example_icons'. I'm rather suspicious of 'nouveau_dri', as I have nvidia drivers installed.

#0  0x00007ffff7e96729 in __GI___poll (fds=0x7fffffffd7f8, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6cb3917 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff6cb562a in xcb_wait_for_special_event ()
   from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff676591b in glPrimitiveBoundingBox ()
   from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#4  0x00007ffff6766b68 in glPrimitiveBoundingBox ()
   from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#5  0x00007ffff6767fe8 in glPrimitiveBoundingBox ()
   from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#6  0x00007ffff54f004a in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#7  0x00007ffff5a03dca in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so

**Comment by svenevs** [comment]
Nouveau is definitely suspicious. Typically for Nvidia drivers it's not enough to just install their driver, you also need to

1. Uninstall nouveau
2. Blacklist the driver and rebuild the kernel boot image

Specific instructions vary by distribution. What flavor of Linux are you using?

**Comment by MylesLeadbeater** [comment]
atm this is ubuntu 19.04,
graphics card is NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1).
I'll look into those instructions, ty. I had no idea where to go on this one

**Comment by MylesLeadbeater** [comment]
after a combination of removing nouveau and installing the latest nvidia drivers, this issue has disappeared. ty =)

**Comment by svenevs** [comment]
Yay! Yeah it's not exactly obvious this has to be done, but now you're "in the know" :)
