### ISSUE TITLE
Using in CLion

### ISSUE THREAD

**Issue by DoStini** [wjakob/nanogui#452]
I've been trying several stuff out, following the compilation guide.
But I don't quite know how to apply it because #include <nanogui> isnt working.
If anyone could give me a light it would be great

This is the project configuration
Project folder

- cmakelists.txt
- ext 
    - nanogui

- src
     - main.cpp

**Comment by DmitruMoth** [comment]
In CMakeLists.txt add include_directories(ext/nanogui/include)
