### ISSUE TITLE
Beginner installation & cmake problems

### ISSUE THREAD

**Issue by juhanikarlsson** [wjakob/nanogui#46]
Yo, 

When working with nanogui whats the best way to deal with cmake and installation? 
Usually with libraries I just make install and find the static libraries from the common library directories. 
With nanogui I could not do this so whats the preferred workflow with multiple projects? ExternalProject_Add? 

Uhhhh Cmake sure gives me a lot of headaches! : )
Thanks, 
- J

**Comment by wjakob** [comment]
Sorry, my resources for support are very limited and this isn't really a nanogui issue. There are plenty of sources of information about cmake, e.g. https://cmake.org/cmake-tutorial/
Just look at some of my other projects like Nori on how to integrate.
