### ISSUE TITLE
mTheme accessed in some widget's constructor

### ISSUE THREAD

**Issue by romp13** [wjakob/nanogui#48]
Hi Wenzel,

Some widgets (in particular Label and Textbox) access mTheme in their constructor. mTheme is however copied from the parent widget otherwise it is a null pointer. This means you cannot create such a widget without parent and attach it later to the GUI. This not a bug per say but it would be convenient as I am doing this regularly in my code.

Thanks!

**Comment by wjakob** [comment]
Hi Romain,

good point, I see how this could be an issue. Do you have any suggestions on how to fix it?

Best,
Wenzel

**Comment by romp13** [comment]
I guess the less invasive fix would be to just check if mTheme is not null in these constructors before accessing these properties and if I want to attach it later I need to set these properties manually.
The better version of this would be to override setParent and/or setTheme for the affected widgets to copy these properties upon attachment to a parent. And I guess this should propagate to children also because otherwise compound widget could be inconsistent. What do you think?
Do you have another idea?
I could prepare a pull request if needed.

Thank you!

**Comment by wjakob** [comment]
Not checking for mTheme seems hacky -- it's also likely that more kinds of properties will migrate from hardcoded constants into the theme in the future.

Having a ``setTheme`` function sounds like a good plan to me (which recursively calls ``setTheme`` on the child widgets). ``setParent`` is less suitable because the parent would just change in one place, so it' odd to propagate that call to the child widgets as well.

**Comment by romp13** [comment]
I agree this sounds like the best option. 
Let me know if I should prepare a pull request or if you prefer to take care of it yourself.

**Comment by wjakob** [comment]
It's not a priority for me. If it causes issues for you then please go ahead and make a PR.

For this kind of interface change, my request would be that you do the change consistently for all widgets :).

**Comment by wjakob** [comment]
also, watch out for the coding style -- no tabs, braces on the same line, etc. Often PRs have to be redone because they are inconsistent with the remainder of the codebase.

**Comment by romp13** [comment]
Yes I'll try my best.
Quick question: should setTheme override properties that have been set
manually? For example for Label should setTheme override mFontSize in all
cases or only if mFontSize < 0? If you prefer the second alternative how to
handle the mColor? Should I checked for the alpha channel being strictly
positive to decide if it has been set manually or not?

**Comment by wjakob** [comment]
PR is finally merged... :)
