### ISSUE TITLE
Crash when clicking on numeric field.

### ISSUE THREAD

**Issue by jr-garcia** [wjakob/nanogui#52]
Clicking inside any editable numeric field crashes the program with:

> Caught exception in event handler: regex_error

Using Ubuntu 14.04 / Nvidia card / OpenGL 3.3

**Comment by almeida91** [comment]
Hello, which compiler are you using?

**Comment by wjakob** [comment]
This is a bug in old versions of the GNU C compiler (specifically, the bundled libstdc++), which do not fully implement the regular expressions header. There are already two old bug reports on this issue, feel free to search the archive.

**Comment by jr-garcia** [comment]
Ok. Thanks. I checked before but did not found the reports, sorry. One is #25 
Problem fixed after upgrading gcc/g++ to 4.9. Thanks again.
