### ISSUE TITLE
Windows cannot be child of non-Screen.

### ISSUE THREAD

**Issue by mcourteaux** [wjakob/nanogui#55]
When you add windows to a Widget (used as panel), they duplicate, because the requestFocus() calls bringWindowToFront() and adds the Window to the children of the Screen.

**Comment by wjakob** [comment]
This kind of usage is not supported by the library. Windows are top-level widgets.

**Comment by mcourteaux** [comment]
Dayum, that's a pitty... Then I'll have to create another fork... Unless you could give me some advice on how to implement a Blender3D-like node editor. I was thinking of using Windows, since they could be dragged around. But maybe I should create a specific widget subclass with the possibility to drag them around.

And if you don't know what the Blender node editor looks like (a quick Google might be helpful), it has nodes (which are basically draggable boxes, with some widgets inside of it) with some input and some output connectors (or sockets whatever you would like to call it). Between nodes, connections can be made from an output of one node to the input of another node.

I'm very new to your library, but I like it a lot so far. Could you give me any tips on how to start designing these classes (basically, what classes should I create, and from what should they inherit) in order to have a clean design? Of course I'm willing to write very specific custom Widgets, I think I just need some guidelines.

Hopefully I'm not asking too much. Thanks in advance, and again thanks for the awesome library :)

**Comment by wjakob** [comment]
Sorry, I don't have the resources to provide support other than severe bugs in the library itself -- you're pretty much on your own.

**Comment by mcourteaux** [comment]
Alright, I guess I'll start reverse engineering the entire codebase then, and figure out for myself what my best bets are... Last question: there is no tutorial, documentation or wiki or anything like that on this project?

**Comment by wjakob** [comment]
There is a basic example app to get started, plus the header files. Contributions in this regard are welcomed.
