### ISSUE TITLE
Remove dependencies?

### ISSUE THREAD

**Issue by fcvarela** [wjakob/nanogui#57]
Hi, is there any reason this packs and builds against its own fork of (at least) glew and glfw? This is very common with ui toolkits (dearimgui notable exception), but it makes it near impossible to use them with any pre-existing app/renderer/engine/etc.

**Comment by wjakob** [comment]
The reason is to make it trivial to drop into a new project and have a GUI from the get-go. Feel free to fork the project and remove them, but I plan to keep the main repository the way it is.

**Comment by fcvarela** [comment]
Got it, makes sense. Thanks!
