### ISSUE TITLE
Popup Button offscreen detection

### ISSUE THREAD

**Issue by ghulands** [wjakob/nanogui#58]
Playing around with the example1, if you move the Basic Widgets window down to the lower right corner of the screen and click the Combobox, you cannot see the sub layout to make a selection. You should detect if the sub layout will have any of its bounds off screen and have it pop from the left side of the control.

**Comment by wjakob** [comment]
If you can implement this in a reasonably compact PR, then I would accept it. However, for me it is not a priority right now.
