### ISSUE TITLE
Incompatible function arguments on user-defined Screen

### ISSUE THREAD

**Issue by mrzv** [wjakob/nanogui#60]
I'm trying to create my own screen class and expose it to Python:
```
struct TestScreen: ng::Screen
{
    void setCallback(const std::function<void()>& c)        {}
};

...

    py::class_<TestScreen>(m, "TestScreen", screen)
      .def(py::init<>())
      .def("setCallback", &TestScreen::setCallback);
```

This works fine, but when I try to `setCallback` from Python:
```
def show():
    print "selected"

s = mymod.TestScreen()
s.setCallback(show)
```
I get:
```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    s.setCallback(show)
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (mymod.TestScreen, std::__1::function<void ()>) -> NoneType
```

What am I doing wrong?

**Comment by wjakob** [comment]
There are lots fancy converters in pybind11 that are entirely optional -- you need to request them explicitly by including a file. In this case, you need to include pybind11/functional.h. The documentation has a detailed list in the "basics" and "advanced" chapters.

**Comment by mrzv** [comment]
Ah, I didn't realize the converters were optional. I think it's time for me to re-read the pybind11 manual. Thanks!

**Comment by wjakob** [comment]
It has grown a lot since you started as an early adopter :)
