### ISSUE TITLE
[Suggestion] Add documentation to the project

### ISSUE THREAD

**Issue by BennetLeff** [wjakob/nanogui#64]
Nanogui seems like a great GUI library for cross platform development. Unfortunately the lack of documentation creates a barrier to entry to developers such as myself. I would love to avoid using a monolithic GUI library like Qt. What can we do to add some documentation? I realize there's already an open suggestion to add instructions to using this library in other code but I think this suggestion would address even more future issues.

**Comment by wjakob** [comment]
I'm open to other people contributing documentation but sadly don't have the resources to work on this myself. There is already another open ticket regarding docs, so I'm closing this one.

**Comment by BennetLeff** [comment]
Fair enough, if I'm able to get going further with the project I'll try adding some documentation.

**Comment by wjakob** [comment]
Thanks to the efforts of Stephen McDowell (@svenevs), we now have documentation!

-> http://nanogui.readthedocs.io/en/latest/?badge=latest
