### ISSUE TITLE
Suggestion: Removing external libraries from this repo

### ISSUE THREAD

**Issue by jslee02** [wjakob/nanogui#67]
I would love to use `nanogui` in my projects for graphical applications. As `nanogui` is, my project is also dependent on Eigen, and it makes a bit difficult to build them together. I understand that having all the external libraries in the same repo is very convenient when developing the library. However, it could cause dependency conflicts when the they have common dependencies.

To avoid this problem, I would like to suggest removing all the external libraries from this repo and changing `nanogui` to build with installed libraries using CMake `find_package`.

If this makes sense to you, then I'm willing to help the change. Please let me know what you think. Thanks!

**Comment by wjakob** [comment]
I'd like to keep the dependencies there to make building the project absolutely straightforward. What I would accept is a PR which adds a flag to the CMakeLists.txt that can be used to specify a directory to an alternative Eigen directory that is used instead.

**Comment by wjakob** [comment]
(Closing this issue, since there is no defect in the software.)
