### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wjakob/nanogui#7]
I would like to point out that identifiers like "[`__NANOGUI_CHECKBOX_H`](https://github.com/wjakob/nanogui/blob/23c2fe8c3bfd189a40773334b4f70da724e025de/include/nanogui/checkbox.h#L1)" and "[`__NANOGUI_GRAPH_H`](https://github.com/wjakob/nanogui/blob/4e8fb09c93cb8699c1e95c2ed21ef0f4ef1ab384/include/nanogui/graph.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wjakob** [comment]
Hi elfring,

what's an officially approved workaround? I'd be tempted to just get rid of the `#ifdef`s and switch to `#pragma once`, but that is not an official extension either, right?

Thanks,
Wenzel

**Comment by elfring** [comment]
How do you think about to delete [the leading underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") from the affected include guards?

**Comment by wjakob** [comment]
fixed.

**Comment by elfring** [comment]
Would you like to reconsider [the reuse](https://github.com/wjakob/nanogui/commit/2d195a80cbb972cee715df7dcdbb1aebed3c6e19#diff-12cd9167a0d4d91e874594135805c1fbL1 "Build system refactoring") of [the construct "`#pragma once`"](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?")?

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/wjakob/nanogui/blob/23206f93390782a41de188131a8d0ef0105a8ea0/src/nanogui.cpp#L19 "More update candidates") left over?
