### ISSUE TITLE
Core dump on integer input parsing.

### ISSUE THREAD

**Issue by r-chris** [wjakob/nanogui#71]
When entering large numbers into fields expecting integers the (example) applications crash with a core dump:

```
Button pressed.
Caught exception in event handler: Could not parse integer value!
Aborted (core dumped)
```

To get there start `./example2` and enter this into the `int` field: `12345678999`
Interestingly float and double fields do not appear to suffer from this problem.
This also doesn't appear to be a problem for the `Positive Integer Mhz` box in `./example1`

**Comment by wjakob** [comment]
good catch, thanks!
