### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [wjakob/nanogui#8]
Extra null pointer checks are not needed in functions like the following.
* [GLShader::free](https://github.com/wjakob/nanogui/blob/23c2fe8c3bfd189a40773334b4f70da724e025de/src/glutil.cpp#L252 "GLShader::free function") ⇒ [glDeleteShader](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glDeleteShader.xml "Do I need to check for NULL before deleting a shader?"), …
* [Widget](https://github.com/wjakob/nanogui/blob/899a6aa411ddd397fcfc182809a43ad087a97178/src/widget.cpp#L20 "Destructor for Widget") ⇒ [delete](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?")

**Comment by wjakob** [comment]
fixed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/wjakob/nanogui/commit/11209d71d2b36e99291f3c655f0bff981d51164a#diff-bb0d9bf315c9ddff7a9a033fa4acdbf6L259 "Deletion of unnecessary checks").
