### ISSUE TITLE
[Suggestion] use the official GLFW

### ISSUE THREAD

**Issue by damiles** [wjakob/nanogui#80]
Hi, why did you point to a customized GLFW and not the lastest version of GLFW, there are new features that are very great to use in 3.2...

Thanks for your support and awesome ui lib

**Comment by wjakob** [comment]
NanoGUI requires a custom GLFW repository with some cmake build system changes. It's no problem to port this to a newer version though -- what's new in 3.2?

**Comment by wjakob** [comment]
switched to 3.2.

**Comment by damiles** [comment]
Thank! i did not reply but some features like choose monitor are very useful when multiple monitors and required one as full screen and other no. Thanks a lot
