### ISSUE TITLE
VS2015 Win32

### ISSUE THREAD

**Issue by dmazzella** [wjakob/nanogui#81]
Hi,
i have problem on build in windows 10 - vs2015 Win32.

command to generate:
cmake -G "Visual Studio 14 2015"  

Error	C2719	'v': formal parameter with requested alignment of 16 won't be aligned	example2	C:\msys64\home\dma\projects\nanogui\include\nanogui\formhelper.h	122	
Error	C2719	'unnamed-parameter': formal parameter with requested alignment of 16 won't be aligned	nanogui_python	C:\msys64\home\dma\projects\nanogui\python\python.cpp	886	
Error	C2719	'<_Args_0>': formal parameter with requested alignment of 16 won't be aligned	example2	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional	276	

any suggestion?

another problem on python/example1.py.
***************
*** 17,23 ****
  from nanogui import Color, Screen, Window, GroupLayout, BoxLayout, \
                      ToolButton, Vector2i, Label, Button, Widget, \
                      PopupButton, CheckBox, MessageDialog, VScrollPanel, \
!                     ImagePanel, ImageView, IntBox, ComboBox, ProgressBar, Slider, \
                      TextBox, ColorWheel, Graph, VectorXf, GridLayout, \
                      Alignment, Orientation, TabWidget
  
--- 17,23 ----
  from nanogui import Color, Screen, Window, GroupLayout, BoxLayout, \
                      ToolButton, Vector2i, Label, Button, Widget, \
                      PopupButton, CheckBox, MessageDialog, VScrollPanel, \
!                     ImagePanel, ImageView, ComboBox, ProgressBar, Slider, \
                      TextBox, ColorWheel, Graph, VectorXf, GridLayout, \
                      Alignment, Orientation, TabWidget
  
missing "IntBox"

Ragards.
D.

**Comment by wjakob** [comment]
Please do a 64 bit build.
