### ISSUE TITLE
(unix) strip command fails when CMAKE_LIBRARY_OUTPUT_DIRECTORY is set

### ISSUE THREAD

**Issue by svenevs** [wjakob/nanogui#85]
I don't understand what this is doing / why

```
if (NANOGUI_BUILD_SHARED AND NOT ${U_CMAKE_BUILD_TYPE} MATCHES DEBUG)
  if (APPLE)
    # Strip .dylib library on OSX
    add_custom_command(TARGET nanogui POST_BUILD COMMAND strip -u -r ${CMAKE_CURRENT_BINARY_DIR}/libnanogui.dylib)
  elseif(UNIX)
    # Strip .so library on Linux
    add_custom_command(TARGET nanogui POST_BUILD COMMAND strip ${CMAKE_CURRENT_BINARY_DIR}/libnanogui.so)
  endif()
endif()
```

I would prefer to continue using a shared library Release build, but the circumstances that be require I set the `CMAKE_LIBRARY_OUTPUT_DIRECTORY`.  So since `libnanogui.*` will get put there rather than `CMAKE_CURRENT_BINARY_DIR`, `strip` will fail.

Does removing the library suffix have a specific purpose?  Would something like the following inside the `NANOGUI_BUILD_SHARED AND NOT ...` section work?

```
get_property(NANOGUI_ALTERNATE_LIBRARY_LOCATION GLOBAL PROPERTY LIBRARY_OUTPUT_DIRECTORY)
if(NANOGUI_ALTERNATE_LIBRARY_LOCATION)
  set(NANOGUI_LIBRARY_DIRECTORY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}"
else()
  set(NANOGUI_LIBRARY_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
endif()
```

and then use `${NANOGUI_LIBRARY_DIRECTORY}/libnanogui...` in each respective branch?

**Comment by wjakob** [comment]
The strip command reduces the size of the generated executable. I'm open to contributions which rewrite the add_custom_command invocations using CMake generator expressions so that it can find the library wherever it ends up. I don't think it's a good idea to introduce a new property for that.

**Comment by svenevs** [comment]
I believe the above PR fixes this, the `CMAKE_*_OUTPUT_DIRECTORY` variables are somewhat under-documented and/or not used consistently throughout the community.  My understanding is nobody building a library should ever be setting these properties, but I didn't realize `get_property` did what it does.

It should be sufficient to just check `if(CMAKE_LIBRARY_OUTPUT_DIRECTORY)`, which is what that PR does.
