### ISSUE TITLE
Combobox setCallback doesn't propagate to children

### ISSUE THREAD

**Issue by mike-1-2-3** [wjakob/nanogui#88]
Unless I'm missing something, the combobox setCallback function only works after you call setItems as well. I assume the intended behavior is to call all of the child buttons' setCallback.

**Comment by wjakob** [comment]
I don't see why this would be the case. The involved lambda functions reference the implicit ``this`` pointer, so they would see a potential update of the callback function.  I'll close the ticket for now -- if you still think that there is a bug, please post a self-contained example which reproduces the issue.

**Comment by mike-1-2-3** [comment]
Ah, sorry. That bug only effects the outdated SDL port. Thanks for the quick response and the beautiful library!
