### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [wjakob/nanogui#9]
Would you like to add more error handling for a call of a function like "[popen](https://github.com/wjakob/nanogui/blob/901a6727eef2014af5c885e42da102b337a8fb2c/src/nanogui.cpp#L205 "Update candidate: file_dialog()")"?

**Comment by wjakob** [comment]
huh? :) -- do you want to submit a pull request? I probably won't get to work on nanogui for a bit.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by wjakob** [comment]
no way! That is total overkill.. :)

**Comment by wjakob** [comment]
fixed.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/wjakob/nanogui/blob/23206f93390782a41de188131a8d0ef0105a8ea0/src/nanogui.cpp#L152 "More update candidates") left over?
