### ISSUE TITLE
VS2015 Eigen alignment issue

### ISSUE THREAD

**Issue by nithins** [wjakob/nanogui#90]
An runtime crash with win32 apps using nanogui (with IGL) crops up with VS2015 (Haven't tested on  other versions). 

Specifically, I managed to trace the issue to the definition of the color definition in common.h . The problem and the quickfix suggested  [here]( https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html) solves this problem. Particularly, adding a compiler "-DEIGEN_DONT_ALIGN_STATICALLY" .

But, I imagine that this flag should NOT be used for optimal Eigen code and is a problem when mixing computational code with the viewer.

**Comment by wjakob** [comment]
The solution is very simple :) -- don't build for 32 bit mode. This issue has already been discussed here many times, and it's really not a nanogui problem, so I'll close this ticket.

**Comment by nithins** [comment]
Ouch, ok. I didn't spot any ticket/issue that said so. My bad. I'm forced
to use 32bit, so I'll stick to my solution. Thanks for the great code
anyway. :)
