### ISSUE TITLE
When GUI widgets are hidden, they still accept mouse commands and input

### ISSUE THREAD

**Issue by AlwaysGeeky** [wjakob/nanogui#93]
I noticed that input commands and other functionality is still being intercepted by widgets that are hidden.

I easily reproduced this by having a checkbox that can be used to turn a parent window on/off (hidden) and you can click it when it is hidden.

**Comment by wjakob** [comment]
I find that surprising -- at least according to the widget code, mouse button events are only propagated to visible children (proof: https://github.com/wjakob/nanogui/blob/master/src/widget.cpp#L85).

Can you be a bit more specific about your setup? A self-contained example that reproduces the problem would be helpful.

**Comment by wjakob** [comment]
ping?

**Comment by AlwaysGeeky** [comment]
Hi, sorry I haven't had a chance to work on this yet, or get a version of the code that demonstrates this behavior...

I do note however what you said seems true, this behavior seems very strange based on the code.

**Comment by wjakob** [comment]
ping?

**Comment by wjakob** [comment]
Closing due to lack of response.
