### ISSUE TITLE
Window not restoring properly after minimization

### ISSUE THREAD

**Issue by joelpp** [wjakob/nanogui#95]
This happens with the examples that come with the library: if I minimize then restore the main window, its size does not restore to the proper thing. It comes back up with a height of 0 and a width just large enough for the title to show.

I think you're not calling glfwSetWindowIconifyCallback anywhere. I just wanted to bring it to your attention and see if you had a fix planned, in the meantime we're keeping track of our window size manually.
Thanks!

**Comment by wjakob** [comment]
I have never encountered this issue before on any OS -- please submit a minimal test example that reproduces this issue along with information on your platform etc.

**Comment by wjakob** [comment]
(Never mind, you said that it happens with the examples)

**Comment by wjakob** [comment]
.. so -- any details on how I can reproduce this? E.g. platform/OS, graphics card make, specific steps? I have just never seen this happen.

**Comment by joelpp** [comment]
I'm running on Windows, using Visual Studio 2015. GPU is a NVIDIA GeForce GTX 670. I don't think I changed anything to the build process.

Anyway thanks to @selfshadow for uncovering the issue!
